// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.3
// source: goclaw/v1/admin.proto

package pbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_GetEngineStatus_FullMethodName = "/goclaw.v1.AdminService/GetEngineStatus"
	AdminService_UpdateConfig_FullMethodName    = "/goclaw.v1.AdminService/UpdateConfig"
	AdminService_ManageCluster_FullMethodName   = "/goclaw.v1.AdminService/ManageCluster"
	AdminService_PauseWorkflows_FullMethodName  = "/goclaw.v1.AdminService/PauseWorkflows"
	AdminService_ResumeWorkflows_FullMethodName = "/goclaw.v1.AdminService/ResumeWorkflows"
	AdminService_PurgeWorkflows_FullMethodName  = "/goclaw.v1.AdminService/PurgeWorkflows"
	AdminService_GetLaneStats_FullMethodName    = "/goclaw.v1.AdminService/GetLaneStats"
	AdminService_ExportMetrics_FullMethodName   = "/goclaw.v1.AdminService/ExportMetrics"
	AdminService_GetDebugInfo_FullMethodName    = "/goclaw.v1.AdminService/GetDebugInfo"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService provides engine administration operations
type AdminServiceClient interface {
	GetEngineStatus(ctx context.Context, in *GetEngineStatusRequest, opts ...grpc.CallOption) (*GetEngineStatusResponse, error)
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error)
	ManageCluster(ctx context.Context, in *ManageClusterRequest, opts ...grpc.CallOption) (*ManageClusterResponse, error)
	PauseWorkflows(ctx context.Context, in *PauseWorkflowsRequest, opts ...grpc.CallOption) (*PauseWorkflowsResponse, error)
	ResumeWorkflows(ctx context.Context, in *ResumeWorkflowsRequest, opts ...grpc.CallOption) (*ResumeWorkflowsResponse, error)
	PurgeWorkflows(ctx context.Context, in *PurgeWorkflowsRequest, opts ...grpc.CallOption) (*PurgeWorkflowsResponse, error)
	GetLaneStats(ctx context.Context, in *GetLaneStatsRequest, opts ...grpc.CallOption) (*GetLaneStatsResponse, error)
	ExportMetrics(ctx context.Context, in *ExportMetricsRequest, opts ...grpc.CallOption) (*ExportMetricsResponse, error)
	GetDebugInfo(ctx context.Context, in *GetDebugInfoRequest, opts ...grpc.CallOption) (*GetDebugInfoResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) GetEngineStatus(ctx context.Context, in *GetEngineStatusRequest, opts ...grpc.CallOption) (*GetEngineStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEngineStatusResponse)
	err := c.cc.Invoke(ctx, AdminService_GetEngineStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConfigResponse)
	err := c.cc.Invoke(ctx, AdminService_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ManageCluster(ctx context.Context, in *ManageClusterRequest, opts ...grpc.CallOption) (*ManageClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManageClusterResponse)
	err := c.cc.Invoke(ctx, AdminService_ManageCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) PauseWorkflows(ctx context.Context, in *PauseWorkflowsRequest, opts ...grpc.CallOption) (*PauseWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseWorkflowsResponse)
	err := c.cc.Invoke(ctx, AdminService_PauseWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ResumeWorkflows(ctx context.Context, in *ResumeWorkflowsRequest, opts ...grpc.CallOption) (*ResumeWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeWorkflowsResponse)
	err := c.cc.Invoke(ctx, AdminService_ResumeWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) PurgeWorkflows(ctx context.Context, in *PurgeWorkflowsRequest, opts ...grpc.CallOption) (*PurgeWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeWorkflowsResponse)
	err := c.cc.Invoke(ctx, AdminService_PurgeWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetLaneStats(ctx context.Context, in *GetLaneStatsRequest, opts ...grpc.CallOption) (*GetLaneStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLaneStatsResponse)
	err := c.cc.Invoke(ctx, AdminService_GetLaneStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ExportMetrics(ctx context.Context, in *ExportMetricsRequest, opts ...grpc.CallOption) (*ExportMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportMetricsResponse)
	err := c.cc.Invoke(ctx, AdminService_ExportMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetDebugInfo(ctx context.Context, in *GetDebugInfoRequest, opts ...grpc.CallOption) (*GetDebugInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDebugInfoResponse)
	err := c.cc.Invoke(ctx, AdminService_GetDebugInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService provides engine administration operations
type AdminServiceServer interface {
	GetEngineStatus(context.Context, *GetEngineStatusRequest) (*GetEngineStatusResponse, error)
	UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error)
	ManageCluster(context.Context, *ManageClusterRequest) (*ManageClusterResponse, error)
	PauseWorkflows(context.Context, *PauseWorkflowsRequest) (*PauseWorkflowsResponse, error)
	ResumeWorkflows(context.Context, *ResumeWorkflowsRequest) (*ResumeWorkflowsResponse, error)
	PurgeWorkflows(context.Context, *PurgeWorkflowsRequest) (*PurgeWorkflowsResponse, error)
	GetLaneStats(context.Context, *GetLaneStatsRequest) (*GetLaneStatsResponse, error)
	ExportMetrics(context.Context, *ExportMetricsRequest) (*ExportMetricsResponse, error)
	GetDebugInfo(context.Context, *GetDebugInfoRequest) (*GetDebugInfoResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) GetEngineStatus(context.Context, *GetEngineStatusRequest) (*GetEngineStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEngineStatus not implemented")
}
func (UnimplementedAdminServiceServer) UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedAdminServiceServer) ManageCluster(context.Context, *ManageClusterRequest) (*ManageClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ManageCluster not implemented")
}
func (UnimplementedAdminServiceServer) PauseWorkflows(context.Context, *PauseWorkflowsRequest) (*PauseWorkflowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseWorkflows not implemented")
}
func (UnimplementedAdminServiceServer) ResumeWorkflows(context.Context, *ResumeWorkflowsRequest) (*ResumeWorkflowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeWorkflows not implemented")
}
func (UnimplementedAdminServiceServer) PurgeWorkflows(context.Context, *PurgeWorkflowsRequest) (*PurgeWorkflowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PurgeWorkflows not implemented")
}
func (UnimplementedAdminServiceServer) GetLaneStats(context.Context, *GetLaneStatsRequest) (*GetLaneStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLaneStats not implemented")
}
func (UnimplementedAdminServiceServer) ExportMetrics(context.Context, *ExportMetricsRequest) (*ExportMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportMetrics not implemented")
}
func (UnimplementedAdminServiceServer) GetDebugInfo(context.Context, *GetDebugInfoRequest) (*GetDebugInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDebugInfo not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_GetEngineStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEngineStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetEngineStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetEngineStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetEngineStatus(ctx, req.(*GetEngineStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ManageCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManageClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ManageCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ManageCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ManageCluster(ctx, req.(*ManageClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_PauseWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).PauseWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_PauseWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).PauseWorkflows(ctx, req.(*PauseWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ResumeWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ResumeWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ResumeWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ResumeWorkflows(ctx, req.(*ResumeWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_PurgeWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).PurgeWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_PurgeWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).PurgeWorkflows(ctx, req.(*PurgeWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetLaneStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLaneStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetLaneStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetLaneStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetLaneStats(ctx, req.(*GetLaneStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ExportMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ExportMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ExportMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ExportMetrics(ctx, req.(*ExportMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetDebugInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDebugInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetDebugInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetDebugInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetDebugInfo(ctx, req.(*GetDebugInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goclaw.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEngineStatus",
			Handler:    _AdminService_GetEngineStatus_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _AdminService_UpdateConfig_Handler,
		},
		{
			MethodName: "ManageCluster",
			Handler:    _AdminService_ManageCluster_Handler,
		},
		{
			MethodName: "PauseWorkflows",
			Handler:    _AdminService_PauseWorkflows_Handler,
		},
		{
			MethodName: "ResumeWorkflows",
			Handler:    _AdminService_ResumeWorkflows_Handler,
		},
		{
			MethodName: "PurgeWorkflows",
			Handler:    _AdminService_PurgeWorkflows_Handler,
		},
		{
			MethodName: "GetLaneStats",
			Handler:    _AdminService_GetLaneStats_Handler,
		},
		{
			MethodName: "ExportMetrics",
			Handler:    _AdminService_ExportMetrics_Handler,
		},
		{
			MethodName: "GetDebugInfo",
			Handler:    _AdminService_GetDebugInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goclaw/v1/admin.proto",
}
