// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: goclaw/v1/admin.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Engine state enum
type EngineState int32

const (
	EngineState_ENGINE_STATE_UNSPECIFIED EngineState = 0
	EngineState_ENGINE_STATE_IDLE        EngineState = 1
	EngineState_ENGINE_STATE_RUNNING     EngineState = 2
	EngineState_ENGINE_STATE_STOPPED     EngineState = 3
	EngineState_ENGINE_STATE_ERROR       EngineState = 4
)

// Enum value maps for EngineState.
var (
	EngineState_name = map[int32]string{
		0: "ENGINE_STATE_UNSPECIFIED",
		1: "ENGINE_STATE_IDLE",
		2: "ENGINE_STATE_RUNNING",
		3: "ENGINE_STATE_STOPPED",
		4: "ENGINE_STATE_ERROR",
	}
	EngineState_value = map[string]int32{
		"ENGINE_STATE_UNSPECIFIED": 0,
		"ENGINE_STATE_IDLE":        1,
		"ENGINE_STATE_RUNNING":     2,
		"ENGINE_STATE_STOPPED":     3,
		"ENGINE_STATE_ERROR":       4,
	}
)

func (x EngineState) Enum() *EngineState {
	p := new(EngineState)
	*p = x
	return p
}

func (x EngineState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EngineState) Descriptor() protoreflect.EnumDescriptor {
	return file_goclaw_v1_admin_proto_enumTypes[0].Descriptor()
}

func (EngineState) Type() protoreflect.EnumType {
	return &file_goclaw_v1_admin_proto_enumTypes[0]
}

func (x EngineState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EngineState.Descriptor instead.
func (EngineState) EnumDescriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{0}
}

// Cluster operation enum
type ClusterOperation int32

const (
	ClusterOperation_CLUSTER_OPERATION_UNSPECIFIED ClusterOperation = 0
	ClusterOperation_CLUSTER_OPERATION_LIST        ClusterOperation = 1
	ClusterOperation_CLUSTER_OPERATION_ADD         ClusterOperation = 2
	ClusterOperation_CLUSTER_OPERATION_REMOVE      ClusterOperation = 3
	ClusterOperation_CLUSTER_OPERATION_PROMOTE     ClusterOperation = 4
)

// Enum value maps for ClusterOperation.
var (
	ClusterOperation_name = map[int32]string{
		0: "CLUSTER_OPERATION_UNSPECIFIED",
		1: "CLUSTER_OPERATION_LIST",
		2: "CLUSTER_OPERATION_ADD",
		3: "CLUSTER_OPERATION_REMOVE",
		4: "CLUSTER_OPERATION_PROMOTE",
	}
	ClusterOperation_value = map[string]int32{
		"CLUSTER_OPERATION_UNSPECIFIED": 0,
		"CLUSTER_OPERATION_LIST":        1,
		"CLUSTER_OPERATION_ADD":         2,
		"CLUSTER_OPERATION_REMOVE":      3,
		"CLUSTER_OPERATION_PROMOTE":     4,
	}
)

func (x ClusterOperation) Enum() *ClusterOperation {
	p := new(ClusterOperation)
	*p = x
	return p
}

func (x ClusterOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_goclaw_v1_admin_proto_enumTypes[1].Descriptor()
}

func (ClusterOperation) Type() protoreflect.EnumType {
	return &file_goclaw_v1_admin_proto_enumTypes[1]
}

func (x ClusterOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterOperation.Descriptor instead.
func (ClusterOperation) EnumDescriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{1}
}

// Metrics format enum
type MetricsFormat int32

const (
	MetricsFormat_METRICS_FORMAT_UNSPECIFIED MetricsFormat = 0
	MetricsFormat_METRICS_FORMAT_PROMETHEUS  MetricsFormat = 1
	MetricsFormat_METRICS_FORMAT_JSON        MetricsFormat = 2
)

// Enum value maps for MetricsFormat.
var (
	MetricsFormat_name = map[int32]string{
		0: "METRICS_FORMAT_UNSPECIFIED",
		1: "METRICS_FORMAT_PROMETHEUS",
		2: "METRICS_FORMAT_JSON",
	}
	MetricsFormat_value = map[string]int32{
		"METRICS_FORMAT_UNSPECIFIED": 0,
		"METRICS_FORMAT_PROMETHEUS":  1,
		"METRICS_FORMAT_JSON":        2,
	}
)

func (x MetricsFormat) Enum() *MetricsFormat {
	p := new(MetricsFormat)
	*p = x
	return p
}

func (x MetricsFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricsFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_goclaw_v1_admin_proto_enumTypes[2].Descriptor()
}

func (MetricsFormat) Type() protoreflect.EnumType {
	return &file_goclaw_v1_admin_proto_enumTypes[2]
}

func (x MetricsFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricsFormat.Descriptor instead.
func (MetricsFormat) EnumDescriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{2}
}

// Debug info type enum
type DebugInfoType int32

const (
	DebugInfoType_DEBUG_INFO_TYPE_UNSPECIFIED DebugInfoType = 0
	DebugInfoType_DEBUG_INFO_TYPE_GOROUTINE   DebugInfoType = 1
	DebugInfoType_DEBUG_INFO_TYPE_HEAP        DebugInfoType = 2
	DebugInfoType_DEBUG_INFO_TYPE_CPU         DebugInfoType = 3
)

// Enum value maps for DebugInfoType.
var (
	DebugInfoType_name = map[int32]string{
		0: "DEBUG_INFO_TYPE_UNSPECIFIED",
		1: "DEBUG_INFO_TYPE_GOROUTINE",
		2: "DEBUG_INFO_TYPE_HEAP",
		3: "DEBUG_INFO_TYPE_CPU",
	}
	DebugInfoType_value = map[string]int32{
		"DEBUG_INFO_TYPE_UNSPECIFIED": 0,
		"DEBUG_INFO_TYPE_GOROUTINE":   1,
		"DEBUG_INFO_TYPE_HEAP":        2,
		"DEBUG_INFO_TYPE_CPU":         3,
	}
)

func (x DebugInfoType) Enum() *DebugInfoType {
	p := new(DebugInfoType)
	*p = x
	return p
}

func (x DebugInfoType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DebugInfoType) Descriptor() protoreflect.EnumDescriptor {
	return file_goclaw_v1_admin_proto_enumTypes[3].Descriptor()
}

func (DebugInfoType) Type() protoreflect.EnumType {
	return &file_goclaw_v1_admin_proto_enumTypes[3]
}

func (x DebugInfoType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DebugInfoType.Descriptor instead.
func (DebugInfoType) EnumDescriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{3}
}

// Get engine status request
type GetEngineStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEngineStatusRequest) Reset() {
	*x = GetEngineStatusRequest{}
	mi := &file_goclaw_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEngineStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEngineStatusRequest) ProtoMessage() {}

func (x *GetEngineStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEngineStatusRequest.ProtoReflect.Descriptor instead.
func (*GetEngineStatusRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{0}
}

// Engine metrics
type EngineMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ActiveWorkflows    int64                  `protobuf:"varint,1,opt,name=active_workflows,json=activeWorkflows,proto3" json:"active_workflows,omitempty"`
	CompletedWorkflows int64                  `protobuf:"varint,2,opt,name=completed_workflows,json=completedWorkflows,proto3" json:"completed_workflows,omitempty"`
	RunningTasks       int64                  `protobuf:"varint,3,opt,name=running_tasks,json=runningTasks,proto3" json:"running_tasks,omitempty"`
	QueueDepth         int64                  `protobuf:"varint,4,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	MemoryUsageBytes   int64                  `protobuf:"varint,5,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	GoroutineCount     int32                  `protobuf:"varint,6,opt,name=goroutine_count,json=goroutineCount,proto3" json:"goroutine_count,omitempty"`
	CpuUsagePercent    float64                `protobuf:"fixed64,7,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EngineMetrics) Reset() {
	*x = EngineMetrics{}
	mi := &file_goclaw_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineMetrics) ProtoMessage() {}

func (x *EngineMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineMetrics.ProtoReflect.Descriptor instead.
func (*EngineMetrics) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *EngineMetrics) GetActiveWorkflows() int64 {
	if x != nil {
		return x.ActiveWorkflows
	}
	return 0
}

func (x *EngineMetrics) GetCompletedWorkflows() int64 {
	if x != nil {
		return x.CompletedWorkflows
	}
	return 0
}

func (x *EngineMetrics) GetRunningTasks() int64 {
	if x != nil {
		return x.RunningTasks
	}
	return 0
}

func (x *EngineMetrics) GetQueueDepth() int64 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *EngineMetrics) GetMemoryUsageBytes() int64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *EngineMetrics) GetGoroutineCount() int32 {
	if x != nil {
		return x.GoroutineCount
	}
	return 0
}

func (x *EngineMetrics) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

// Get engine status response
type GetEngineStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         EngineState            `protobuf:"varint,1,opt,name=state,proto3,enum=goclaw.v1.EngineState" json:"state,omitempty"`
	Metrics       *EngineMetrics         `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	UptimeSince   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=uptime_since,json=uptimeSince,proto3" json:"uptime_since,omitempty"`
	LastError     string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Healthy       bool                   `protobuf:"varint,5,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Error         *Error                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEngineStatusResponse) Reset() {
	*x = GetEngineStatusResponse{}
	mi := &file_goclaw_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEngineStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEngineStatusResponse) ProtoMessage() {}

func (x *GetEngineStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEngineStatusResponse.ProtoReflect.Descriptor instead.
func (*GetEngineStatusResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *GetEngineStatusResponse) GetState() EngineState {
	if x != nil {
		return x.State
	}
	return EngineState_ENGINE_STATE_UNSPECIFIED
}

func (x *GetEngineStatusResponse) GetMetrics() *EngineMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *GetEngineStatusResponse) GetUptimeSince() *timestamppb.Timestamp {
	if x != nil {
		return x.UptimeSince
	}
	return nil
}

func (x *GetEngineStatusResponse) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *GetEngineStatusResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *GetEngineStatusResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Update config request
type UpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigUpdates map[string]string      `protobuf:"bytes,1,rep,name=config_updates,json=configUpdates,proto3" json:"config_updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Persist       bool                   `protobuf:"varint,2,opt,name=persist,proto3" json:"persist,omitempty"`
	DryRun        bool                   `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_goclaw_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateConfigRequest) GetConfigUpdates() map[string]string {
	if x != nil {
		return x.ConfigUpdates
	}
	return nil
}

func (x *UpdateConfigRequest) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

func (x *UpdateConfigRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

// Update config response
type UpdateConfigResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AppliedChanges map[string]string      `protobuf:"bytes,2,rep,name=applied_changes,json=appliedChanges,proto3" json:"applied_changes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error          *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_goclaw_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateConfigResponse) GetAppliedChanges() map[string]string {
	if x != nil {
		return x.AppliedChanges
	}
	return nil
}

func (x *UpdateConfigResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Cluster node info
type ClusterNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Healthy       bool                   `protobuf:"varint,4,opt,name=healthy,proto3" json:"healthy,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterNode) Reset() {
	*x = ClusterNode{}
	mi := &file_goclaw_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterNode) ProtoMessage() {}

func (x *ClusterNode) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterNode.ProtoReflect.Descriptor instead.
func (*ClusterNode) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ClusterNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ClusterNode) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ClusterNode) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ClusterNode) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ClusterNode) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

// Manage cluster request
type ManageClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     ClusterOperation       `protobuf:"varint,1,opt,name=operation,proto3,enum=goclaw.v1.ClusterOperation" json:"operation,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeAddress   string                 `protobuf:"bytes,3,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	Confirmation  bool                   `protobuf:"varint,4,opt,name=confirmation,proto3" json:"confirmation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageClusterRequest) Reset() {
	*x = ManageClusterRequest{}
	mi := &file_goclaw_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageClusterRequest) ProtoMessage() {}

func (x *ManageClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageClusterRequest.ProtoReflect.Descriptor instead.
func (*ManageClusterRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *ManageClusterRequest) GetOperation() ClusterOperation {
	if x != nil {
		return x.Operation
	}
	return ClusterOperation_CLUSTER_OPERATION_UNSPECIFIED
}

func (x *ManageClusterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ManageClusterRequest) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

func (x *ManageClusterRequest) GetConfirmation() bool {
	if x != nil {
		return x.Confirmation
	}
	return false
}

// Manage cluster response
type ManageClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Nodes         []*ClusterNode         `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageClusterResponse) Reset() {
	*x = ManageClusterResponse{}
	mi := &file_goclaw_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageClusterResponse) ProtoMessage() {}

func (x *ManageClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageClusterResponse.ProtoReflect.Descriptor instead.
func (*ManageClusterResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ManageClusterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ManageClusterResponse) GetNodes() []*ClusterNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ManageClusterResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Pause workflows request
type PauseWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirmation  bool                   `protobuf:"varint,1,opt,name=confirmation,proto3" json:"confirmation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseWorkflowsRequest) Reset() {
	*x = PauseWorkflowsRequest{}
	mi := &file_goclaw_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseWorkflowsRequest) ProtoMessage() {}

func (x *PauseWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*PauseWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *PauseWorkflowsRequest) GetConfirmation() bool {
	if x != nil {
		return x.Confirmation
	}
	return false
}

// Pause workflows response
type PauseWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PausedCount   int32                  `protobuf:"varint,2,opt,name=paused_count,json=pausedCount,proto3" json:"paused_count,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseWorkflowsResponse) Reset() {
	*x = PauseWorkflowsResponse{}
	mi := &file_goclaw_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseWorkflowsResponse) ProtoMessage() {}

func (x *PauseWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*PauseWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *PauseWorkflowsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PauseWorkflowsResponse) GetPausedCount() int32 {
	if x != nil {
		return x.PausedCount
	}
	return 0
}

func (x *PauseWorkflowsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Resume workflows request
type ResumeWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeWorkflowsRequest) Reset() {
	*x = ResumeWorkflowsRequest{}
	mi := &file_goclaw_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeWorkflowsRequest) ProtoMessage() {}

func (x *ResumeWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ResumeWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{10}
}

// Resume workflows response
type ResumeWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ResumedCount  int32                  `protobuf:"varint,2,opt,name=resumed_count,json=resumedCount,proto3" json:"resumed_count,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeWorkflowsResponse) Reset() {
	*x = ResumeWorkflowsResponse{}
	mi := &file_goclaw_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeWorkflowsResponse) ProtoMessage() {}

func (x *ResumeWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ResumeWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *ResumeWorkflowsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResumeWorkflowsResponse) GetResumedCount() int32 {
	if x != nil {
		return x.ResumedCount
	}
	return 0
}

func (x *ResumeWorkflowsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Purge workflows request
type PurgeWorkflowsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgeThresholdHours int32                  `protobuf:"varint,1,opt,name=age_threshold_hours,json=ageThresholdHours,proto3" json:"age_threshold_hours,omitempty"`
	Confirmation      bool                   `protobuf:"varint,2,opt,name=confirmation,proto3" json:"confirmation,omitempty"`
	DryRun            bool                   `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PurgeWorkflowsRequest) Reset() {
	*x = PurgeWorkflowsRequest{}
	mi := &file_goclaw_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeWorkflowsRequest) ProtoMessage() {}

func (x *PurgeWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*PurgeWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *PurgeWorkflowsRequest) GetAgeThresholdHours() int32 {
	if x != nil {
		return x.AgeThresholdHours
	}
	return 0
}

func (x *PurgeWorkflowsRequest) GetConfirmation() bool {
	if x != nil {
		return x.Confirmation
	}
	return false
}

func (x *PurgeWorkflowsRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

// Purge workflows response
type PurgeWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PurgedCount   int32                  `protobuf:"varint,2,opt,name=purged_count,json=purgedCount,proto3" json:"purged_count,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeWorkflowsResponse) Reset() {
	*x = PurgeWorkflowsResponse{}
	mi := &file_goclaw_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeWorkflowsResponse) ProtoMessage() {}

func (x *PurgeWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*PurgeWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *PurgeWorkflowsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PurgeWorkflowsResponse) GetPurgedCount() int32 {
	if x != nil {
		return x.PurgedCount
	}
	return 0
}

func (x *PurgeWorkflowsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Get lane stats request
type GetLaneStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LaneName      string                 `protobuf:"bytes,1,opt,name=lane_name,json=laneName,proto3" json:"lane_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLaneStatsRequest) Reset() {
	*x = GetLaneStatsRequest{}
	mi := &file_goclaw_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLaneStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLaneStatsRequest) ProtoMessage() {}

func (x *GetLaneStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLaneStatsRequest.ProtoReflect.Descriptor instead.
func (*GetLaneStatsRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *GetLaneStatsRequest) GetLaneName() string {
	if x != nil {
		return x.LaneName
	}
	return ""
}

// Lane statistics
type LaneStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LaneName         string                 `protobuf:"bytes,1,opt,name=lane_name,json=laneName,proto3" json:"lane_name,omitempty"`
	QueueDepth       int32                  `protobuf:"varint,2,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	WorkerCount      int32                  `protobuf:"varint,3,opt,name=worker_count,json=workerCount,proto3" json:"worker_count,omitempty"`
	ThroughputPerSec float64                `protobuf:"fixed64,4,opt,name=throughput_per_sec,json=throughputPerSec,proto3" json:"throughput_per_sec,omitempty"`
	ErrorRate        float64                `protobuf:"fixed64,5,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LaneStats) Reset() {
	*x = LaneStats{}
	mi := &file_goclaw_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaneStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaneStats) ProtoMessage() {}

func (x *LaneStats) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaneStats.ProtoReflect.Descriptor instead.
func (*LaneStats) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *LaneStats) GetLaneName() string {
	if x != nil {
		return x.LaneName
	}
	return ""
}

func (x *LaneStats) GetQueueDepth() int32 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *LaneStats) GetWorkerCount() int32 {
	if x != nil {
		return x.WorkerCount
	}
	return 0
}

func (x *LaneStats) GetThroughputPerSec() float64 {
	if x != nil {
		return x.ThroughputPerSec
	}
	return 0
}

func (x *LaneStats) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

// Get lane stats response
type GetLaneStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lanes         []*LaneStats           `protobuf:"bytes,1,rep,name=lanes,proto3" json:"lanes,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLaneStatsResponse) Reset() {
	*x = GetLaneStatsResponse{}
	mi := &file_goclaw_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLaneStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLaneStatsResponse) ProtoMessage() {}

func (x *GetLaneStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLaneStatsResponse.ProtoReflect.Descriptor instead.
func (*GetLaneStatsResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *GetLaneStatsResponse) GetLanes() []*LaneStats {
	if x != nil {
		return x.Lanes
	}
	return nil
}

func (x *GetLaneStatsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Export metrics request
type ExportMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        MetricsFormat          `protobuf:"varint,1,opt,name=format,proto3,enum=goclaw.v1.MetricsFormat" json:"format,omitempty"`
	PrefixFilter  string                 `protobuf:"bytes,2,opt,name=prefix_filter,json=prefixFilter,proto3" json:"prefix_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportMetricsRequest) Reset() {
	*x = ExportMetricsRequest{}
	mi := &file_goclaw_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportMetricsRequest) ProtoMessage() {}

func (x *ExportMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportMetricsRequest.ProtoReflect.Descriptor instead.
func (*ExportMetricsRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *ExportMetricsRequest) GetFormat() MetricsFormat {
	if x != nil {
		return x.Format
	}
	return MetricsFormat_METRICS_FORMAT_UNSPECIFIED
}

func (x *ExportMetricsRequest) GetPrefixFilter() string {
	if x != nil {
		return x.PrefixFilter
	}
	return ""
}

// Export metrics response
type ExportMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricsData   string                 `protobuf:"bytes,1,opt,name=metrics_data,json=metricsData,proto3" json:"metrics_data,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportMetricsResponse) Reset() {
	*x = ExportMetricsResponse{}
	mi := &file_goclaw_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportMetricsResponse) ProtoMessage() {}

func (x *ExportMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportMetricsResponse.ProtoReflect.Descriptor instead.
func (*ExportMetricsResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{18}
}

func (x *ExportMetricsResponse) GetMetricsData() string {
	if x != nil {
		return x.MetricsData
	}
	return ""
}

func (x *ExportMetricsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Get debug info request
type GetDebugInfoRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            DebugInfoType          `protobuf:"varint,1,opt,name=type,proto3,enum=goclaw.v1.DebugInfoType" json:"type,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,2,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetDebugInfoRequest) Reset() {
	*x = GetDebugInfoRequest{}
	mi := &file_goclaw_v1_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDebugInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDebugInfoRequest) ProtoMessage() {}

func (x *GetDebugInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDebugInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDebugInfoRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{19}
}

func (x *GetDebugInfoRequest) GetType() DebugInfoType {
	if x != nil {
		return x.Type
	}
	return DebugInfoType_DEBUG_INFO_TYPE_UNSPECIFIED
}

func (x *GetDebugInfoRequest) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

// Get debug info response
type GetDebugInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DebugData     []byte                 `protobuf:"bytes,1,opt,name=debug_data,json=debugData,proto3" json:"debug_data,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDebugInfoResponse) Reset() {
	*x = GetDebugInfoResponse{}
	mi := &file_goclaw_v1_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDebugInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDebugInfoResponse) ProtoMessage() {}

func (x *GetDebugInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDebugInfoResponse.ProtoReflect.Descriptor instead.
func (*GetDebugInfoResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_admin_proto_rawDescGZIP(), []int{20}
}

func (x *GetDebugInfoResponse) GetDebugData() []byte {
	if x != nil {
		return x.DebugData
	}
	return nil
}

func (x *GetDebugInfoResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_goclaw_v1_admin_proto protoreflect.FileDescriptor

const file_goclaw_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x15goclaw/v1/admin.proto\x12\tgoclaw.v1\x1a\x16goclaw/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x18\n" +
	"\x16GetEngineStatusRequest\"\xb4\x02\n" +
	"\rEngineMetrics\x12)\n" +
	"\x10active_workflows\x18\x01 \x01(\x03R\x0factiveWorkflows\x12/\n" +
	"\x13completed_workflows\x18\x02 \x01(\x03R\x12completedWorkflows\x12#\n" +
	"\rrunning_tasks\x18\x03 \x01(\x03R\frunningTasks\x12\x1f\n" +
	"\vqueue_depth\x18\x04 \x01(\x03R\n" +
	"queueDepth\x12,\n" +
	"\x12memory_usage_bytes\x18\x05 \x01(\x03R\x10memoryUsageBytes\x12'\n" +
	"\x0fgoroutine_count\x18\x06 \x01(\x05R\x0egoroutineCount\x12*\n" +
	"\x11cpu_usage_percent\x18\a \x01(\x01R\x0fcpuUsagePercent\"\x9b\x02\n" +
	"\x17GetEngineStatusResponse\x12,\n" +
	"\x05state\x18\x01 \x01(\x0e2\x16.goclaw.v1.EngineStateR\x05state\x122\n" +
	"\ametrics\x18\x02 \x01(\v2\x18.goclaw.v1.EngineMetricsR\ametrics\x12=\n" +
	"\fuptime_since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vuptimeSince\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\x12\x18\n" +
	"\ahealthy\x18\x05 \x01(\bR\ahealthy\x12&\n" +
	"\x05error\x18\x06 \x01(\v2\x10.goclaw.v1.ErrorR\x05error\"\xe4\x01\n" +
	"\x13UpdateConfigRequest\x12X\n" +
	"\x0econfig_updates\x18\x01 \x03(\v21.goclaw.v1.UpdateConfigRequest.ConfigUpdatesEntryR\rconfigUpdates\x12\x18\n" +
	"\apersist\x18\x02 \x01(\bR\apersist\x12\x17\n" +
	"\adry_run\x18\x03 \x01(\bR\x06dryRun\x1a@\n" +
	"\x12ConfigUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x01\n" +
	"\x14UpdateConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\\\n" +
	"\x0fapplied_changes\x18\x02 \x03(\v23.goclaw.v1.UpdateConfigResponse.AppliedChangesEntryR\x0eappliedChanges\x12&\n" +
	"\x05error\x18\x03 \x01(\v2\x10.goclaw.v1.ErrorR\x05error\x1aA\n" +
	"\x13AppliedChangesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x01\n" +
	"\vClusterNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x18\n" +
	"\ahealthy\x18\x04 \x01(\bR\ahealthy\x127\n" +
	"\tjoined_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\"\xb1\x01\n" +
	"\x14ManageClusterRequest\x129\n" +
	"\toperation\x18\x01 \x01(\x0e2\x1b.goclaw.v1.ClusterOperationR\toperation\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12!\n" +
	"\fnode_address\x18\x03 \x01(\tR\vnodeAddress\x12\"\n" +
	"\fconfirmation\x18\x04 \x01(\bR\fconfirmation\"\x87\x01\n" +
	"\x15ManageClusterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\x05nodes\x18\x02 \x03(\v2\x16.goclaw.v1.ClusterNodeR\x05nodes\x12&\n" +
	"\x05error\x18\x03 \x01(\v2\x10.goclaw.v1.ErrorR\x05error\";\n" +
	"\x15PauseWorkflowsRequest\x12\"\n" +
	"\fconfirmation\x18\x01 \x01(\bR\fconfirmation\"}\n" +
	"\x16PauseWorkflowsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fpaused_count\x18\x02 \x01(\x05R\vpausedCount\x12&\n" +
	"\x05error\x18\x03 \x01(\v2\x10.goclaw.v1.ErrorR\x05error\"\x18\n" +
	"\x16ResumeWorkflowsRequest\"\x80\x01\n" +
	"\x17ResumeWorkflowsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rresumed_count\x18\x02 \x01(\x05R\fresumedCount\x12&\n" +
	"\x05error\x18\x03 \x01(\v2\x10.goclaw.v1.ErrorR\x05error\"\x84\x01\n" +
	"\x15PurgeWorkflowsRequest\x12.\n" +
	"\x13age_threshold_hours\x18\x01 \x01(\x05R\x11ageThresholdHours\x12\"\n" +
	"\fconfirmation\x18\x02 \x01(\bR\fconfirmation\x12\x17\n" +
	"\adry_run\x18\x03 \x01(\bR\x06dryRun\"}\n" +
	"\x16PurgeWorkflowsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fpurged_count\x18\x02 \x01(\x05R\vpurgedCount\x12&\n" +
	"\x05error\x18\x03 \x01(\v2\x10.goclaw.v1.ErrorR\x05error\"2\n" +
	"\x13GetLaneStatsRequest\x12\x1b\n" +
	"\tlane_name\x18\x01 \x01(\tR\blaneName\"\xb9\x01\n" +
	"\tLaneStats\x12\x1b\n" +
	"\tlane_name\x18\x01 \x01(\tR\blaneName\x12\x1f\n" +
	"\vqueue_depth\x18\x02 \x01(\x05R\n" +
	"queueDepth\x12!\n" +
	"\fworker_count\x18\x03 \x01(\x05R\vworkerCount\x12,\n" +
	"\x12throughput_per_sec\x18\x04 \x01(\x01R\x10throughputPerSec\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x05 \x01(\x01R\terrorRate\"j\n" +
	"\x14GetLaneStatsResponse\x12*\n" +
	"\x05lanes\x18\x01 \x03(\v2\x14.goclaw.v1.LaneStatsR\x05lanes\x12&\n" +
	"\x05error\x18\x02 \x01(\v2\x10.goclaw.v1.ErrorR\x05error\"m\n" +
	"\x14ExportMetricsRequest\x120\n" +
	"\x06format\x18\x01 \x01(\x0e2\x18.goclaw.v1.MetricsFormatR\x06format\x12#\n" +
	"\rprefix_filter\x18\x02 \x01(\tR\fprefixFilter\"b\n" +
	"\x15ExportMetricsResponse\x12!\n" +
	"\fmetrics_data\x18\x01 \x01(\tR\vmetricsData\x12&\n" +
	"\x05error\x18\x02 \x01(\v2\x10.goclaw.v1.ErrorR\x05error\"n\n" +
	"\x13GetDebugInfoRequest\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.goclaw.v1.DebugInfoTypeR\x04type\x12)\n" +
	"\x10duration_seconds\x18\x02 \x01(\x05R\x0fdurationSeconds\"]\n" +
	"\x14GetDebugInfoResponse\x12\x1d\n" +
	"\n" +
	"debug_data\x18\x01 \x01(\fR\tdebugData\x12&\n" +
	"\x05error\x18\x02 \x01(\v2\x10.goclaw.v1.ErrorR\x05error*\x8e\x01\n" +
	"\vEngineState\x12\x1c\n" +
	"\x18ENGINE_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ENGINE_STATE_IDLE\x10\x01\x12\x18\n" +
	"\x14ENGINE_STATE_RUNNING\x10\x02\x12\x18\n" +
	"\x14ENGINE_STATE_STOPPED\x10\x03\x12\x16\n" +
	"\x12ENGINE_STATE_ERROR\x10\x04*\xa9\x01\n" +
	"\x10ClusterOperation\x12!\n" +
	"\x1dCLUSTER_OPERATION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CLUSTER_OPERATION_LIST\x10\x01\x12\x19\n" +
	"\x15CLUSTER_OPERATION_ADD\x10\x02\x12\x1c\n" +
	"\x18CLUSTER_OPERATION_REMOVE\x10\x03\x12\x1d\n" +
	"\x19CLUSTER_OPERATION_PROMOTE\x10\x04*g\n" +
	"\rMetricsFormat\x12\x1e\n" +
	"\x1aMETRICS_FORMAT_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19METRICS_FORMAT_PROMETHEUS\x10\x01\x12\x17\n" +
	"\x13METRICS_FORMAT_JSON\x10\x02*\x82\x01\n" +
	"\rDebugInfoType\x12\x1f\n" +
	"\x1bDEBUG_INFO_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19DEBUG_INFO_TYPE_GOROUTINE\x10\x01\x12\x18\n" +
	"\x14DEBUG_INFO_TYPE_HEAP\x10\x02\x12\x17\n" +
	"\x13DEBUG_INFO_TYPE_CPU\x10\x032\x8b\x06\n" +
	"\fAdminService\x12X\n" +
	"\x0fGetEngineStatus\x12!.goclaw.v1.GetEngineStatusRequest\x1a\".goclaw.v1.GetEngineStatusResponse\x12O\n" +
	"\fUpdateConfig\x12\x1e.goclaw.v1.UpdateConfigRequest\x1a\x1f.goclaw.v1.UpdateConfigResponse\x12R\n" +
	"\rManageCluster\x12\x1f.goclaw.v1.ManageClusterRequest\x1a .goclaw.v1.ManageClusterResponse\x12U\n" +
	"\x0ePauseWorkflows\x12 .goclaw.v1.PauseWorkflowsRequest\x1a!.goclaw.v1.PauseWorkflowsResponse\x12X\n" +
	"\x0fResumeWorkflows\x12!.goclaw.v1.ResumeWorkflowsRequest\x1a\".goclaw.v1.ResumeWorkflowsResponse\x12U\n" +
	"\x0ePurgeWorkflows\x12 .goclaw.v1.PurgeWorkflowsRequest\x1a!.goclaw.v1.PurgeWorkflowsResponse\x12O\n" +
	"\fGetLaneStats\x12\x1e.goclaw.v1.GetLaneStatsRequest\x1a\x1f.goclaw.v1.GetLaneStatsResponse\x12R\n" +
	"\rExportMetrics\x12\x1f.goclaw.v1.ExportMetricsRequest\x1a .goclaw.v1.ExportMetricsResponse\x12O\n" +
	"\fGetDebugInfo\x12\x1e.goclaw.v1.GetDebugInfoRequest\x1a\x1f.goclaw.v1.GetDebugInfoResponseB.Z,github.com/goclaw/goclaw/pkg/grpc/pb/v1;pbv1b\x06proto3"

var (
	file_goclaw_v1_admin_proto_rawDescOnce sync.Once
	file_goclaw_v1_admin_proto_rawDescData []byte
)

func file_goclaw_v1_admin_proto_rawDescGZIP() []byte {
	file_goclaw_v1_admin_proto_rawDescOnce.Do(func() {
		file_goclaw_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goclaw_v1_admin_proto_rawDesc), len(file_goclaw_v1_admin_proto_rawDesc)))
	})
	return file_goclaw_v1_admin_proto_rawDescData
}

var file_goclaw_v1_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_goclaw_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_goclaw_v1_admin_proto_goTypes = []any{
	(EngineState)(0),                // 0: goclaw.v1.EngineState
	(ClusterOperation)(0),           // 1: goclaw.v1.ClusterOperation
	(MetricsFormat)(0),              // 2: goclaw.v1.MetricsFormat
	(DebugInfoType)(0),              // 3: goclaw.v1.DebugInfoType
	(*GetEngineStatusRequest)(nil),  // 4: goclaw.v1.GetEngineStatusRequest
	(*EngineMetrics)(nil),           // 5: goclaw.v1.EngineMetrics
	(*GetEngineStatusResponse)(nil), // 6: goclaw.v1.GetEngineStatusResponse
	(*UpdateConfigRequest)(nil),     // 7: goclaw.v1.UpdateConfigRequest
	(*UpdateConfigResponse)(nil),    // 8: goclaw.v1.UpdateConfigResponse
	(*ClusterNode)(nil),             // 9: goclaw.v1.ClusterNode
	(*ManageClusterRequest)(nil),    // 10: goclaw.v1.ManageClusterRequest
	(*ManageClusterResponse)(nil),   // 11: goclaw.v1.ManageClusterResponse
	(*PauseWorkflowsRequest)(nil),   // 12: goclaw.v1.PauseWorkflowsRequest
	(*PauseWorkflowsResponse)(nil),  // 13: goclaw.v1.PauseWorkflowsResponse
	(*ResumeWorkflowsRequest)(nil),  // 14: goclaw.v1.ResumeWorkflowsRequest
	(*ResumeWorkflowsResponse)(nil), // 15: goclaw.v1.ResumeWorkflowsResponse
	(*PurgeWorkflowsRequest)(nil),   // 16: goclaw.v1.PurgeWorkflowsRequest
	(*PurgeWorkflowsResponse)(nil),  // 17: goclaw.v1.PurgeWorkflowsResponse
	(*GetLaneStatsRequest)(nil),     // 18: goclaw.v1.GetLaneStatsRequest
	(*LaneStats)(nil),               // 19: goclaw.v1.LaneStats
	(*GetLaneStatsResponse)(nil),    // 20: goclaw.v1.GetLaneStatsResponse
	(*ExportMetricsRequest)(nil),    // 21: goclaw.v1.ExportMetricsRequest
	(*ExportMetricsResponse)(nil),   // 22: goclaw.v1.ExportMetricsResponse
	(*GetDebugInfoRequest)(nil),     // 23: goclaw.v1.GetDebugInfoRequest
	(*GetDebugInfoResponse)(nil),    // 24: goclaw.v1.GetDebugInfoResponse
	nil,                             // 25: goclaw.v1.UpdateConfigRequest.ConfigUpdatesEntry
	nil,                             // 26: goclaw.v1.UpdateConfigResponse.AppliedChangesEntry
	(*timestamppb.Timestamp)(nil),   // 27: google.protobuf.Timestamp
	(*Error)(nil),                   // 28: goclaw.v1.Error
}
var file_goclaw_v1_admin_proto_depIdxs = []int32{
	0,  // 0: goclaw.v1.GetEngineStatusResponse.state:type_name -> goclaw.v1.EngineState
	5,  // 1: goclaw.v1.GetEngineStatusResponse.metrics:type_name -> goclaw.v1.EngineMetrics
	27, // 2: goclaw.v1.GetEngineStatusResponse.uptime_since:type_name -> google.protobuf.Timestamp
	28, // 3: goclaw.v1.GetEngineStatusResponse.error:type_name -> goclaw.v1.Error
	25, // 4: goclaw.v1.UpdateConfigRequest.config_updates:type_name -> goclaw.v1.UpdateConfigRequest.ConfigUpdatesEntry
	26, // 5: goclaw.v1.UpdateConfigResponse.applied_changes:type_name -> goclaw.v1.UpdateConfigResponse.AppliedChangesEntry
	28, // 6: goclaw.v1.UpdateConfigResponse.error:type_name -> goclaw.v1.Error
	27, // 7: goclaw.v1.ClusterNode.joined_at:type_name -> google.protobuf.Timestamp
	1,  // 8: goclaw.v1.ManageClusterRequest.operation:type_name -> goclaw.v1.ClusterOperation
	9,  // 9: goclaw.v1.ManageClusterResponse.nodes:type_name -> goclaw.v1.ClusterNode
	28, // 10: goclaw.v1.ManageClusterResponse.error:type_name -> goclaw.v1.Error
	28, // 11: goclaw.v1.PauseWorkflowsResponse.error:type_name -> goclaw.v1.Error
	28, // 12: goclaw.v1.ResumeWorkflowsResponse.error:type_name -> goclaw.v1.Error
	28, // 13: goclaw.v1.PurgeWorkflowsResponse.error:type_name -> goclaw.v1.Error
	19, // 14: goclaw.v1.GetLaneStatsResponse.lanes:type_name -> goclaw.v1.LaneStats
	28, // 15: goclaw.v1.GetLaneStatsResponse.error:type_name -> goclaw.v1.Error
	2,  // 16: goclaw.v1.ExportMetricsRequest.format:type_name -> goclaw.v1.MetricsFormat
	28, // 17: goclaw.v1.ExportMetricsResponse.error:type_name -> goclaw.v1.Error
	3,  // 18: goclaw.v1.GetDebugInfoRequest.type:type_name -> goclaw.v1.DebugInfoType
	28, // 19: goclaw.v1.GetDebugInfoResponse.error:type_name -> goclaw.v1.Error
	4,  // 20: goclaw.v1.AdminService.GetEngineStatus:input_type -> goclaw.v1.GetEngineStatusRequest
	7,  // 21: goclaw.v1.AdminService.UpdateConfig:input_type -> goclaw.v1.UpdateConfigRequest
	10, // 22: goclaw.v1.AdminService.ManageCluster:input_type -> goclaw.v1.ManageClusterRequest
	12, // 23: goclaw.v1.AdminService.PauseWorkflows:input_type -> goclaw.v1.PauseWorkflowsRequest
	14, // 24: goclaw.v1.AdminService.ResumeWorkflows:input_type -> goclaw.v1.ResumeWorkflowsRequest
	16, // 25: goclaw.v1.AdminService.PurgeWorkflows:input_type -> goclaw.v1.PurgeWorkflowsRequest
	18, // 26: goclaw.v1.AdminService.GetLaneStats:input_type -> goclaw.v1.GetLaneStatsRequest
	21, // 27: goclaw.v1.AdminService.ExportMetrics:input_type -> goclaw.v1.ExportMetricsRequest
	23, // 28: goclaw.v1.AdminService.GetDebugInfo:input_type -> goclaw.v1.GetDebugInfoRequest
	6,  // 29: goclaw.v1.AdminService.GetEngineStatus:output_type -> goclaw.v1.GetEngineStatusResponse
	8,  // 30: goclaw.v1.AdminService.UpdateConfig:output_type -> goclaw.v1.UpdateConfigResponse
	11, // 31: goclaw.v1.AdminService.ManageCluster:output_type -> goclaw.v1.ManageClusterResponse
	13, // 32: goclaw.v1.AdminService.PauseWorkflows:output_type -> goclaw.v1.PauseWorkflowsResponse
	15, // 33: goclaw.v1.AdminService.ResumeWorkflows:output_type -> goclaw.v1.ResumeWorkflowsResponse
	17, // 34: goclaw.v1.AdminService.PurgeWorkflows:output_type -> goclaw.v1.PurgeWorkflowsResponse
	20, // 35: goclaw.v1.AdminService.GetLaneStats:output_type -> goclaw.v1.GetLaneStatsResponse
	22, // 36: goclaw.v1.AdminService.ExportMetrics:output_type -> goclaw.v1.ExportMetricsResponse
	24, // 37: goclaw.v1.AdminService.GetDebugInfo:output_type -> goclaw.v1.GetDebugInfoResponse
	29, // [29:38] is the sub-list for method output_type
	20, // [20:29] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_goclaw_v1_admin_proto_init() }
func file_goclaw_v1_admin_proto_init() {
	if File_goclaw_v1_admin_proto != nil {
		return
	}
	file_goclaw_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goclaw_v1_admin_proto_rawDesc), len(file_goclaw_v1_admin_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goclaw_v1_admin_proto_goTypes,
		DependencyIndexes: file_goclaw_v1_admin_proto_depIdxs,
		EnumInfos:         file_goclaw_v1_admin_proto_enumTypes,
		MessageInfos:      file_goclaw_v1_admin_proto_msgTypes,
	}.Build()
	File_goclaw_v1_admin_proto = out.File
	file_goclaw_v1_admin_proto_goTypes = nil
	file_goclaw_v1_admin_proto_depIdxs = nil
}
