// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.3
// source: goclaw/v1/batch.proto

package pbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BatchService_SubmitWorkflows_FullMethodName     = "/goclaw.v1.BatchService/SubmitWorkflows"
	BatchService_GetWorkflowStatuses_FullMethodName = "/goclaw.v1.BatchService/GetWorkflowStatuses"
	BatchService_CancelWorkflows_FullMethodName     = "/goclaw.v1.BatchService/CancelWorkflows"
	BatchService_GetTaskResults_FullMethodName      = "/goclaw.v1.BatchService/GetTaskResults"
)

// BatchServiceClient is the client API for BatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BatchService provides bulk workflow operations
type BatchServiceClient interface {
	SubmitWorkflows(ctx context.Context, in *SubmitWorkflowsRequest, opts ...grpc.CallOption) (*SubmitWorkflowsResponse, error)
	GetWorkflowStatuses(ctx context.Context, in *GetWorkflowStatusesRequest, opts ...grpc.CallOption) (*GetWorkflowStatusesResponse, error)
	CancelWorkflows(ctx context.Context, in *CancelWorkflowsRequest, opts ...grpc.CallOption) (*CancelWorkflowsResponse, error)
	GetTaskResults(ctx context.Context, in *GetTaskResultsRequest, opts ...grpc.CallOption) (*GetTaskResultsResponse, error)
}

type batchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBatchServiceClient(cc grpc.ClientConnInterface) BatchServiceClient {
	return &batchServiceClient{cc}
}

func (c *batchServiceClient) SubmitWorkflows(ctx context.Context, in *SubmitWorkflowsRequest, opts ...grpc.CallOption) (*SubmitWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitWorkflowsResponse)
	err := c.cc.Invoke(ctx, BatchService_SubmitWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *batchServiceClient) GetWorkflowStatuses(ctx context.Context, in *GetWorkflowStatusesRequest, opts ...grpc.CallOption) (*GetWorkflowStatusesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkflowStatusesResponse)
	err := c.cc.Invoke(ctx, BatchService_GetWorkflowStatuses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *batchServiceClient) CancelWorkflows(ctx context.Context, in *CancelWorkflowsRequest, opts ...grpc.CallOption) (*CancelWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelWorkflowsResponse)
	err := c.cc.Invoke(ctx, BatchService_CancelWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *batchServiceClient) GetTaskResults(ctx context.Context, in *GetTaskResultsRequest, opts ...grpc.CallOption) (*GetTaskResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskResultsResponse)
	err := c.cc.Invoke(ctx, BatchService_GetTaskResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BatchServiceServer is the server API for BatchService service.
// All implementations must embed UnimplementedBatchServiceServer
// for forward compatibility.
//
// BatchService provides bulk workflow operations
type BatchServiceServer interface {
	SubmitWorkflows(context.Context, *SubmitWorkflowsRequest) (*SubmitWorkflowsResponse, error)
	GetWorkflowStatuses(context.Context, *GetWorkflowStatusesRequest) (*GetWorkflowStatusesResponse, error)
	CancelWorkflows(context.Context, *CancelWorkflowsRequest) (*CancelWorkflowsResponse, error)
	GetTaskResults(context.Context, *GetTaskResultsRequest) (*GetTaskResultsResponse, error)
	mustEmbedUnimplementedBatchServiceServer()
}

// UnimplementedBatchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBatchServiceServer struct{}

func (UnimplementedBatchServiceServer) SubmitWorkflows(context.Context, *SubmitWorkflowsRequest) (*SubmitWorkflowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitWorkflows not implemented")
}
func (UnimplementedBatchServiceServer) GetWorkflowStatuses(context.Context, *GetWorkflowStatusesRequest) (*GetWorkflowStatusesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkflowStatuses not implemented")
}
func (UnimplementedBatchServiceServer) CancelWorkflows(context.Context, *CancelWorkflowsRequest) (*CancelWorkflowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelWorkflows not implemented")
}
func (UnimplementedBatchServiceServer) GetTaskResults(context.Context, *GetTaskResultsRequest) (*GetTaskResultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskResults not implemented")
}
func (UnimplementedBatchServiceServer) mustEmbedUnimplementedBatchServiceServer() {}
func (UnimplementedBatchServiceServer) testEmbeddedByValue()                      {}

// UnsafeBatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BatchServiceServer will
// result in compilation errors.
type UnsafeBatchServiceServer interface {
	mustEmbedUnimplementedBatchServiceServer()
}

func RegisterBatchServiceServer(s grpc.ServiceRegistrar, srv BatchServiceServer) {
	// If the following call panics, it indicates UnimplementedBatchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BatchService_ServiceDesc, srv)
}

func _BatchService_SubmitWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchServiceServer).SubmitWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BatchService_SubmitWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchServiceServer).SubmitWorkflows(ctx, req.(*SubmitWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BatchService_GetWorkflowStatuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowStatusesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchServiceServer).GetWorkflowStatuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BatchService_GetWorkflowStatuses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchServiceServer).GetWorkflowStatuses(ctx, req.(*GetWorkflowStatusesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BatchService_CancelWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchServiceServer).CancelWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BatchService_CancelWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchServiceServer).CancelWorkflows(ctx, req.(*CancelWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BatchService_GetTaskResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchServiceServer).GetTaskResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BatchService_GetTaskResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchServiceServer).GetTaskResults(ctx, req.(*GetTaskResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BatchService_ServiceDesc is the grpc.ServiceDesc for BatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goclaw.v1.BatchService",
	HandlerType: (*BatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitWorkflows",
			Handler:    _BatchService_SubmitWorkflows_Handler,
		},
		{
			MethodName: "GetWorkflowStatuses",
			Handler:    _BatchService_GetWorkflowStatuses_Handler,
		},
		{
			MethodName: "CancelWorkflows",
			Handler:    _BatchService_CancelWorkflows_Handler,
		},
		{
			MethodName: "GetTaskResults",
			Handler:    _BatchService_GetTaskResults_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goclaw/v1/batch.proto",
}
