// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: goclaw/v1/batch.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Submit workflows request
type SubmitWorkflowsRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Workflows      []*SubmitWorkflowRequest `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	Atomic         bool                     `protobuf:"varint,2,opt,name=atomic,proto3" json:"atomic,omitempty"`
	IdempotencyKey string                   `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Ordered        bool                     `protobuf:"varint,4,opt,name=ordered,proto3" json:"ordered,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitWorkflowsRequest) Reset() {
	*x = SubmitWorkflowsRequest{}
	mi := &file_goclaw_v1_batch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWorkflowsRequest) ProtoMessage() {}

func (x *SubmitWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_batch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*SubmitWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_batch_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitWorkflowsRequest) GetWorkflows() []*SubmitWorkflowRequest {
	if x != nil {
		return x.Workflows
	}
	return nil
}

func (x *SubmitWorkflowsRequest) GetAtomic() bool {
	if x != nil {
		return x.Atomic
	}
	return false
}

func (x *SubmitWorkflowsRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SubmitWorkflowsRequest) GetOrdered() bool {
	if x != nil {
		return x.Ordered
	}
	return false
}

// Workflow submission result
type WorkflowSubmissionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,3,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Error         *Error                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowSubmissionResult) Reset() {
	*x = WorkflowSubmissionResult{}
	mi := &file_goclaw_v1_batch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowSubmissionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowSubmissionResult) ProtoMessage() {}

func (x *WorkflowSubmissionResult) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_batch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowSubmissionResult.ProtoReflect.Descriptor instead.
func (*WorkflowSubmissionResult) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_batch_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowSubmissionResult) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *WorkflowSubmissionResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WorkflowSubmissionResult) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowSubmissionResult) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Submit workflows response
type SubmitWorkflowsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Results       []*WorkflowSubmissionResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Pagination    *PaginationResponse         `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Error         *Error                      `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWorkflowsResponse) Reset() {
	*x = SubmitWorkflowsResponse{}
	mi := &file_goclaw_v1_batch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWorkflowsResponse) ProtoMessage() {}

func (x *SubmitWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_batch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*SubmitWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_batch_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitWorkflowsResponse) GetResults() []*WorkflowSubmissionResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SubmitWorkflowsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *SubmitWorkflowsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Get workflow statuses request
type GetWorkflowStatusesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowIds   []string               `protobuf:"bytes,1,rep,name=workflow_ids,json=workflowIds,proto3" json:"workflow_ids,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowStatusesRequest) Reset() {
	*x = GetWorkflowStatusesRequest{}
	mi := &file_goclaw_v1_batch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowStatusesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowStatusesRequest) ProtoMessage() {}

func (x *GetWorkflowStatusesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_batch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowStatusesRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowStatusesRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_batch_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorkflowStatusesRequest) GetWorkflowIds() []string {
	if x != nil {
		return x.WorkflowIds
	}
	return nil
}

func (x *GetWorkflowStatusesRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Workflow status result
type WorkflowStatusResult struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	WorkflowId    string                     `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Found         bool                       `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Status        *GetWorkflowStatusResponse `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Error         *Error                     `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowStatusResult) Reset() {
	*x = WorkflowStatusResult{}
	mi := &file_goclaw_v1_batch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStatusResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStatusResult) ProtoMessage() {}

func (x *WorkflowStatusResult) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_batch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStatusResult.ProtoReflect.Descriptor instead.
func (*WorkflowStatusResult) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_batch_proto_rawDescGZIP(), []int{4}
}

func (x *WorkflowStatusResult) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowStatusResult) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *WorkflowStatusResult) GetStatus() *GetWorkflowStatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *WorkflowStatusResult) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Get workflow statuses response
type GetWorkflowStatusesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Results       []*WorkflowStatusResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Pagination    *PaginationResponse     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Error         *Error                  `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowStatusesResponse) Reset() {
	*x = GetWorkflowStatusesResponse{}
	mi := &file_goclaw_v1_batch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowStatusesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowStatusesResponse) ProtoMessage() {}

func (x *GetWorkflowStatusesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_batch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowStatusesResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowStatusesResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_batch_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorkflowStatusesResponse) GetResults() []*WorkflowStatusResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetWorkflowStatusesResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetWorkflowStatusesResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Cancel workflows request
type CancelWorkflowsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkflowIds    []string               `protobuf:"bytes,1,rep,name=workflow_ids,json=workflowIds,proto3" json:"workflow_ids,omitempty"`
	Force          bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelWorkflowsRequest) Reset() {
	*x = CancelWorkflowsRequest{}
	mi := &file_goclaw_v1_batch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowsRequest) ProtoMessage() {}

func (x *CancelWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_batch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*CancelWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_batch_proto_rawDescGZIP(), []int{6}
}

func (x *CancelWorkflowsRequest) GetWorkflowIds() []string {
	if x != nil {
		return x.WorkflowIds
	}
	return nil
}

func (x *CancelWorkflowsRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *CancelWorkflowsRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// Workflow cancellation result
type WorkflowCancellationResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId      string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Success         bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	AlreadyTerminal bool                   `protobuf:"varint,3,opt,name=already_terminal,json=alreadyTerminal,proto3" json:"already_terminal,omitempty"`
	Error           *Error                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkflowCancellationResult) Reset() {
	*x = WorkflowCancellationResult{}
	mi := &file_goclaw_v1_batch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowCancellationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowCancellationResult) ProtoMessage() {}

func (x *WorkflowCancellationResult) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_batch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowCancellationResult.ProtoReflect.Descriptor instead.
func (*WorkflowCancellationResult) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_batch_proto_rawDescGZIP(), []int{7}
}

func (x *WorkflowCancellationResult) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowCancellationResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WorkflowCancellationResult) GetAlreadyTerminal() bool {
	if x != nil {
		return x.AlreadyTerminal
	}
	return false
}

func (x *WorkflowCancellationResult) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Cancel workflows response
type CancelWorkflowsResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Results       []*WorkflowCancellationResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Error         *Error                        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflowsResponse) Reset() {
	*x = CancelWorkflowsResponse{}
	mi := &file_goclaw_v1_batch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowsResponse) ProtoMessage() {}

func (x *CancelWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_batch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*CancelWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_batch_proto_rawDescGZIP(), []int{8}
}

func (x *CancelWorkflowsResponse) GetResults() []*WorkflowCancellationResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *CancelWorkflowsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Get task results request
type GetTaskResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	TaskIds       []string               `protobuf:"bytes,2,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResultsRequest) Reset() {
	*x = GetTaskResultsRequest{}
	mi := &file_goclaw_v1_batch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResultsRequest) ProtoMessage() {}

func (x *GetTaskResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_batch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResultsRequest.ProtoReflect.Descriptor instead.
func (*GetTaskResultsRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_batch_proto_rawDescGZIP(), []int{9}
}

func (x *GetTaskResultsRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *GetTaskResultsRequest) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

func (x *GetTaskResultsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Task result detail
type TaskResultDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Result        *GetTaskResultResponse `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Error         *Error                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultDetail) Reset() {
	*x = TaskResultDetail{}
	mi := &file_goclaw_v1_batch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultDetail) ProtoMessage() {}

func (x *TaskResultDetail) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_batch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultDetail.ProtoReflect.Descriptor instead.
func (*TaskResultDetail) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_batch_proto_rawDescGZIP(), []int{10}
}

func (x *TaskResultDetail) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResultDetail) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *TaskResultDetail) GetResult() *GetTaskResultResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TaskResultDetail) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Get task results response
type GetTaskResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*TaskResultDetail    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResultsResponse) Reset() {
	*x = GetTaskResultsResponse{}
	mi := &file_goclaw_v1_batch_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResultsResponse) ProtoMessage() {}

func (x *GetTaskResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_batch_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResultsResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResultsResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_batch_proto_rawDescGZIP(), []int{11}
}

func (x *GetTaskResultsResponse) GetResults() []*TaskResultDetail {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetTaskResultsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetTaskResultsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_goclaw_v1_batch_proto protoreflect.FileDescriptor

const file_goclaw_v1_batch_proto_rawDesc = "" +
	"\n" +
	"\x15goclaw/v1/batch.proto\x12\tgoclaw.v1\x1a\x16goclaw/v1/common.proto\x1a\x18goclaw/v1/workflow.proto\"\xb3\x01\n" +
	"\x16SubmitWorkflowsRequest\x12>\n" +
	"\tworkflows\x18\x01 \x03(\v2 .goclaw.v1.SubmitWorkflowRequestR\tworkflows\x12\x16\n" +
	"\x06atomic\x18\x02 \x01(\bR\x06atomic\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12\x18\n" +
	"\aordered\x18\x04 \x01(\bR\aordered\"\x93\x01\n" +
	"\x18WorkflowSubmissionResult\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1f\n" +
	"\vworkflow_id\x18\x03 \x01(\tR\n" +
	"workflowId\x12&\n" +
	"\x05error\x18\x04 \x01(\v2\x10.goclaw.v1.ErrorR\x05error\"\xbf\x01\n" +
	"\x17SubmitWorkflowsResponse\x12=\n" +
	"\aresults\x18\x01 \x03(\v2#.goclaw.v1.WorkflowSubmissionResultR\aresults\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.goclaw.v1.PaginationResponseR\n" +
	"pagination\x12&\n" +
	"\x05error\x18\x03 \x01(\v2\x10.goclaw.v1.ErrorR\x05error\"}\n" +
	"\x1aGetWorkflowStatusesRequest\x12!\n" +
	"\fworkflow_ids\x18\x01 \x03(\tR\vworkflowIds\x12<\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1c.goclaw.v1.PaginationRequestR\n" +
	"pagination\"\xb3\x01\n" +
	"\x14WorkflowStatusResult\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12<\n" +
	"\x06status\x18\x03 \x01(\v2$.goclaw.v1.GetWorkflowStatusResponseR\x06status\x12&\n" +
	"\x05error\x18\x04 \x01(\v2\x10.goclaw.v1.ErrorR\x05error\"\xbf\x01\n" +
	"\x1bGetWorkflowStatusesResponse\x129\n" +
	"\aresults\x18\x01 \x03(\v2\x1f.goclaw.v1.WorkflowStatusResultR\aresults\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.goclaw.v1.PaginationResponseR\n" +
	"pagination\x12&\n" +
	"\x05error\x18\x03 \x01(\v2\x10.goclaw.v1.ErrorR\x05error\"z\n" +
	"\x16CancelWorkflowsRequest\x12!\n" +
	"\fworkflow_ids\x18\x01 \x03(\tR\vworkflowIds\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"\xaa\x01\n" +
	"\x1aWorkflowCancellationResult\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12)\n" +
	"\x10already_terminal\x18\x03 \x01(\bR\x0falreadyTerminal\x12&\n" +
	"\x05error\x18\x04 \x01(\v2\x10.goclaw.v1.ErrorR\x05error\"\x82\x01\n" +
	"\x17CancelWorkflowsResponse\x12?\n" +
	"\aresults\x18\x01 \x03(\v2%.goclaw.v1.WorkflowCancellationResultR\aresults\x12&\n" +
	"\x05error\x18\x02 \x01(\v2\x10.goclaw.v1.ErrorR\x05error\"\x91\x01\n" +
	"\x15GetTaskResultsRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x19\n" +
	"\btask_ids\x18\x02 \x03(\tR\ataskIds\x12<\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1c.goclaw.v1.PaginationRequestR\n" +
	"pagination\"\xa3\x01\n" +
	"\x10TaskResultDetail\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x128\n" +
	"\x06result\x18\x03 \x01(\v2 .goclaw.v1.GetTaskResultResponseR\x06result\x12&\n" +
	"\x05error\x18\x04 \x01(\v2\x10.goclaw.v1.ErrorR\x05error\"\xb6\x01\n" +
	"\x16GetTaskResultsResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.goclaw.v1.TaskResultDetailR\aresults\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.goclaw.v1.PaginationResponseR\n" +
	"pagination\x12&\n" +
	"\x05error\x18\x03 \x01(\v2\x10.goclaw.v1.ErrorR\x05error2\xff\x02\n" +
	"\fBatchService\x12X\n" +
	"\x0fSubmitWorkflows\x12!.goclaw.v1.SubmitWorkflowsRequest\x1a\".goclaw.v1.SubmitWorkflowsResponse\x12d\n" +
	"\x13GetWorkflowStatuses\x12%.goclaw.v1.GetWorkflowStatusesRequest\x1a&.goclaw.v1.GetWorkflowStatusesResponse\x12X\n" +
	"\x0fCancelWorkflows\x12!.goclaw.v1.CancelWorkflowsRequest\x1a\".goclaw.v1.CancelWorkflowsResponse\x12U\n" +
	"\x0eGetTaskResults\x12 .goclaw.v1.GetTaskResultsRequest\x1a!.goclaw.v1.GetTaskResultsResponseB.Z,github.com/goclaw/goclaw/pkg/grpc/pb/v1;pbv1b\x06proto3"

var (
	file_goclaw_v1_batch_proto_rawDescOnce sync.Once
	file_goclaw_v1_batch_proto_rawDescData []byte
)

func file_goclaw_v1_batch_proto_rawDescGZIP() []byte {
	file_goclaw_v1_batch_proto_rawDescOnce.Do(func() {
		file_goclaw_v1_batch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goclaw_v1_batch_proto_rawDesc), len(file_goclaw_v1_batch_proto_rawDesc)))
	})
	return file_goclaw_v1_batch_proto_rawDescData
}

var file_goclaw_v1_batch_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_goclaw_v1_batch_proto_goTypes = []any{
	(*SubmitWorkflowsRequest)(nil),      // 0: goclaw.v1.SubmitWorkflowsRequest
	(*WorkflowSubmissionResult)(nil),    // 1: goclaw.v1.WorkflowSubmissionResult
	(*SubmitWorkflowsResponse)(nil),     // 2: goclaw.v1.SubmitWorkflowsResponse
	(*GetWorkflowStatusesRequest)(nil),  // 3: goclaw.v1.GetWorkflowStatusesRequest
	(*WorkflowStatusResult)(nil),        // 4: goclaw.v1.WorkflowStatusResult
	(*GetWorkflowStatusesResponse)(nil), // 5: goclaw.v1.GetWorkflowStatusesResponse
	(*CancelWorkflowsRequest)(nil),      // 6: goclaw.v1.CancelWorkflowsRequest
	(*WorkflowCancellationResult)(nil),  // 7: goclaw.v1.WorkflowCancellationResult
	(*CancelWorkflowsResponse)(nil),     // 8: goclaw.v1.CancelWorkflowsResponse
	(*GetTaskResultsRequest)(nil),       // 9: goclaw.v1.GetTaskResultsRequest
	(*TaskResultDetail)(nil),            // 10: goclaw.v1.TaskResultDetail
	(*GetTaskResultsResponse)(nil),      // 11: goclaw.v1.GetTaskResultsResponse
	(*SubmitWorkflowRequest)(nil),       // 12: goclaw.v1.SubmitWorkflowRequest
	(*Error)(nil),                       // 13: goclaw.v1.Error
	(*PaginationResponse)(nil),          // 14: goclaw.v1.PaginationResponse
	(*PaginationRequest)(nil),           // 15: goclaw.v1.PaginationRequest
	(*GetWorkflowStatusResponse)(nil),   // 16: goclaw.v1.GetWorkflowStatusResponse
	(*GetTaskResultResponse)(nil),       // 17: goclaw.v1.GetTaskResultResponse
}
var file_goclaw_v1_batch_proto_depIdxs = []int32{
	12, // 0: goclaw.v1.SubmitWorkflowsRequest.workflows:type_name -> goclaw.v1.SubmitWorkflowRequest
	13, // 1: goclaw.v1.WorkflowSubmissionResult.error:type_name -> goclaw.v1.Error
	1,  // 2: goclaw.v1.SubmitWorkflowsResponse.results:type_name -> goclaw.v1.WorkflowSubmissionResult
	14, // 3: goclaw.v1.SubmitWorkflowsResponse.pagination:type_name -> goclaw.v1.PaginationResponse
	13, // 4: goclaw.v1.SubmitWorkflowsResponse.error:type_name -> goclaw.v1.Error
	15, // 5: goclaw.v1.GetWorkflowStatusesRequest.pagination:type_name -> goclaw.v1.PaginationRequest
	16, // 6: goclaw.v1.WorkflowStatusResult.status:type_name -> goclaw.v1.GetWorkflowStatusResponse
	13, // 7: goclaw.v1.WorkflowStatusResult.error:type_name -> goclaw.v1.Error
	4,  // 8: goclaw.v1.GetWorkflowStatusesResponse.results:type_name -> goclaw.v1.WorkflowStatusResult
	14, // 9: goclaw.v1.GetWorkflowStatusesResponse.pagination:type_name -> goclaw.v1.PaginationResponse
	13, // 10: goclaw.v1.GetWorkflowStatusesResponse.error:type_name -> goclaw.v1.Error
	13, // 11: goclaw.v1.WorkflowCancellationResult.error:type_name -> goclaw.v1.Error
	7,  // 12: goclaw.v1.CancelWorkflowsResponse.results:type_name -> goclaw.v1.WorkflowCancellationResult
	13, // 13: goclaw.v1.CancelWorkflowsResponse.error:type_name -> goclaw.v1.Error
	15, // 14: goclaw.v1.GetTaskResultsRequest.pagination:type_name -> goclaw.v1.PaginationRequest
	17, // 15: goclaw.v1.TaskResultDetail.result:type_name -> goclaw.v1.GetTaskResultResponse
	13, // 16: goclaw.v1.TaskResultDetail.error:type_name -> goclaw.v1.Error
	10, // 17: goclaw.v1.GetTaskResultsResponse.results:type_name -> goclaw.v1.TaskResultDetail
	14, // 18: goclaw.v1.GetTaskResultsResponse.pagination:type_name -> goclaw.v1.PaginationResponse
	13, // 19: goclaw.v1.GetTaskResultsResponse.error:type_name -> goclaw.v1.Error
	0,  // 20: goclaw.v1.BatchService.SubmitWorkflows:input_type -> goclaw.v1.SubmitWorkflowsRequest
	3,  // 21: goclaw.v1.BatchService.GetWorkflowStatuses:input_type -> goclaw.v1.GetWorkflowStatusesRequest
	6,  // 22: goclaw.v1.BatchService.CancelWorkflows:input_type -> goclaw.v1.CancelWorkflowsRequest
	9,  // 23: goclaw.v1.BatchService.GetTaskResults:input_type -> goclaw.v1.GetTaskResultsRequest
	2,  // 24: goclaw.v1.BatchService.SubmitWorkflows:output_type -> goclaw.v1.SubmitWorkflowsResponse
	5,  // 25: goclaw.v1.BatchService.GetWorkflowStatuses:output_type -> goclaw.v1.GetWorkflowStatusesResponse
	8,  // 26: goclaw.v1.BatchService.CancelWorkflows:output_type -> goclaw.v1.CancelWorkflowsResponse
	11, // 27: goclaw.v1.BatchService.GetTaskResults:output_type -> goclaw.v1.GetTaskResultsResponse
	24, // [24:28] is the sub-list for method output_type
	20, // [20:24] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_goclaw_v1_batch_proto_init() }
func file_goclaw_v1_batch_proto_init() {
	if File_goclaw_v1_batch_proto != nil {
		return
	}
	file_goclaw_v1_common_proto_init()
	file_goclaw_v1_workflow_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goclaw_v1_batch_proto_rawDesc), len(file_goclaw_v1_batch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goclaw_v1_batch_proto_goTypes,
		DependencyIndexes: file_goclaw_v1_batch_proto_depIdxs,
		MessageInfos:      file_goclaw_v1_batch_proto_msgTypes,
	}.Build()
	File_goclaw_v1_batch_proto = out.File
	file_goclaw_v1_batch_proto_goTypes = nil
	file_goclaw_v1_batch_proto_depIdxs = nil
}
