// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: goclaw/v1/saga.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Saga runtime state.
type SagaState int32

const (
	SagaState_SAGA_STATE_UNSPECIFIED          SagaState = 0
	SagaState_SAGA_STATE_CREATED              SagaState = 1
	SagaState_SAGA_STATE_RUNNING              SagaState = 2
	SagaState_SAGA_STATE_COMPLETED            SagaState = 3
	SagaState_SAGA_STATE_COMPENSATING         SagaState = 4
	SagaState_SAGA_STATE_PENDING_COMPENSATION SagaState = 5
	SagaState_SAGA_STATE_COMPENSATED          SagaState = 6
	SagaState_SAGA_STATE_COMPENSATION_FAILED  SagaState = 7
	SagaState_SAGA_STATE_RECOVERING           SagaState = 8
)

// Enum value maps for SagaState.
var (
	SagaState_name = map[int32]string{
		0: "SAGA_STATE_UNSPECIFIED",
		1: "SAGA_STATE_CREATED",
		2: "SAGA_STATE_RUNNING",
		3: "SAGA_STATE_COMPLETED",
		4: "SAGA_STATE_COMPENSATING",
		5: "SAGA_STATE_PENDING_COMPENSATION",
		6: "SAGA_STATE_COMPENSATED",
		7: "SAGA_STATE_COMPENSATION_FAILED",
		8: "SAGA_STATE_RECOVERING",
	}
	SagaState_value = map[string]int32{
		"SAGA_STATE_UNSPECIFIED":          0,
		"SAGA_STATE_CREATED":              1,
		"SAGA_STATE_RUNNING":              2,
		"SAGA_STATE_COMPLETED":            3,
		"SAGA_STATE_COMPENSATING":         4,
		"SAGA_STATE_PENDING_COMPENSATION": 5,
		"SAGA_STATE_COMPENSATED":          6,
		"SAGA_STATE_COMPENSATION_FAILED":  7,
		"SAGA_STATE_RECOVERING":           8,
	}
)

func (x SagaState) Enum() *SagaState {
	p := new(SagaState)
	*p = x
	return p
}

func (x SagaState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SagaState) Descriptor() protoreflect.EnumDescriptor {
	return file_goclaw_v1_saga_proto_enumTypes[0].Descriptor()
}

func (SagaState) Type() protoreflect.EnumType {
	return &file_goclaw_v1_saga_proto_enumTypes[0]
}

func (x SagaState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SagaState.Descriptor instead.
func (SagaState) EnumDescriptor() ([]byte, []int) {
	return file_goclaw_v1_saga_proto_rawDescGZIP(), []int{0}
}

// Compensation policy for saga execution.
type SagaCompensationPolicy int32

const (
	SagaCompensationPolicy_SAGA_COMPENSATION_POLICY_UNSPECIFIED SagaCompensationPolicy = 0
	SagaCompensationPolicy_SAGA_COMPENSATION_POLICY_AUTO        SagaCompensationPolicy = 1
	SagaCompensationPolicy_SAGA_COMPENSATION_POLICY_MANUAL      SagaCompensationPolicy = 2
	SagaCompensationPolicy_SAGA_COMPENSATION_POLICY_SKIP        SagaCompensationPolicy = 3
)

// Enum value maps for SagaCompensationPolicy.
var (
	SagaCompensationPolicy_name = map[int32]string{
		0: "SAGA_COMPENSATION_POLICY_UNSPECIFIED",
		1: "SAGA_COMPENSATION_POLICY_AUTO",
		2: "SAGA_COMPENSATION_POLICY_MANUAL",
		3: "SAGA_COMPENSATION_POLICY_SKIP",
	}
	SagaCompensationPolicy_value = map[string]int32{
		"SAGA_COMPENSATION_POLICY_UNSPECIFIED": 0,
		"SAGA_COMPENSATION_POLICY_AUTO":        1,
		"SAGA_COMPENSATION_POLICY_MANUAL":      2,
		"SAGA_COMPENSATION_POLICY_SKIP":        3,
	}
)

func (x SagaCompensationPolicy) Enum() *SagaCompensationPolicy {
	p := new(SagaCompensationPolicy)
	*p = x
	return p
}

func (x SagaCompensationPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SagaCompensationPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_goclaw_v1_saga_proto_enumTypes[1].Descriptor()
}

func (SagaCompensationPolicy) Type() protoreflect.EnumType {
	return &file_goclaw_v1_saga_proto_enumTypes[1]
}

func (x SagaCompensationPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SagaCompensationPolicy.Descriptor instead.
func (SagaCompensationPolicy) EnumDescriptor() ([]byte, []int) {
	return file_goclaw_v1_saga_proto_rawDescGZIP(), []int{1}
}

// One step in a saga definition.
type SagaStepDefinition struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DependsOn          []string               `protobuf:"bytes,2,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	DelayMs            int32                  `protobuf:"varint,3,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	ShouldFail         bool                   `protobuf:"varint,4,opt,name=should_fail,json=shouldFail,proto3" json:"should_fail,omitempty"`
	TimeoutMs          int32                  `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	EnableCompensation bool                   `protobuf:"varint,6,opt,name=enable_compensation,json=enableCompensation,proto3" json:"enable_compensation,omitempty"`
	SkipCompensation   bool                   `protobuf:"varint,7,opt,name=skip_compensation,json=skipCompensation,proto3" json:"skip_compensation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SagaStepDefinition) Reset() {
	*x = SagaStepDefinition{}
	mi := &file_goclaw_v1_saga_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SagaStepDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SagaStepDefinition) ProtoMessage() {}

func (x *SagaStepDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_saga_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SagaStepDefinition.ProtoReflect.Descriptor instead.
func (*SagaStepDefinition) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_saga_proto_rawDescGZIP(), []int{0}
}

func (x *SagaStepDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SagaStepDefinition) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *SagaStepDefinition) GetDelayMs() int32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

func (x *SagaStepDefinition) GetShouldFail() bool {
	if x != nil {
		return x.ShouldFail
	}
	return false
}

func (x *SagaStepDefinition) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *SagaStepDefinition) GetEnableCompensation() bool {
	if x != nil {
		return x.EnableCompensation
	}
	return false
}

func (x *SagaStepDefinition) GetSkipCompensation() bool {
	if x != nil {
		return x.SkipCompensation
	}
	return false
}

// Submit a saga for execution.
type SubmitSagaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Policy        SagaCompensationPolicy `protobuf:"varint,2,opt,name=policy,proto3,enum=goclaw.v1.SagaCompensationPolicy" json:"policy,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	StepTimeoutMs int32                  `protobuf:"varint,4,opt,name=step_timeout_ms,json=stepTimeoutMs,proto3" json:"step_timeout_ms,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Input         *structpb.Struct       `protobuf:"bytes,6,opt,name=input,proto3" json:"input,omitempty"`
	Steps         []*SagaStepDefinition  `protobuf:"bytes,7,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitSagaRequest) Reset() {
	*x = SubmitSagaRequest{}
	mi := &file_goclaw_v1_saga_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSagaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSagaRequest) ProtoMessage() {}

func (x *SubmitSagaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_saga_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSagaRequest.ProtoReflect.Descriptor instead.
func (*SubmitSagaRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_saga_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitSagaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubmitSagaRequest) GetPolicy() SagaCompensationPolicy {
	if x != nil {
		return x.Policy
	}
	return SagaCompensationPolicy_SAGA_COMPENSATION_POLICY_UNSPECIFIED
}

func (x *SubmitSagaRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *SubmitSagaRequest) GetStepTimeoutMs() int32 {
	if x != nil {
		return x.StepTimeoutMs
	}
	return 0
}

func (x *SubmitSagaRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SubmitSagaRequest) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *SubmitSagaRequest) GetSteps() []*SagaStepDefinition {
	if x != nil {
		return x.Steps
	}
	return nil
}

type SubmitSagaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State         SagaState              `protobuf:"varint,3,opt,name=state,proto3,enum=goclaw.v1.SagaState" json:"state,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitSagaResponse) Reset() {
	*x = SubmitSagaResponse{}
	mi := &file_goclaw_v1_saga_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSagaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSagaResponse) ProtoMessage() {}

func (x *SubmitSagaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_saga_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSagaResponse.ProtoReflect.Descriptor instead.
func (*SubmitSagaResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_saga_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitSagaResponse) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *SubmitSagaResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubmitSagaResponse) GetState() SagaState {
	if x != nil {
		return x.State
	}
	return SagaState_SAGA_STATE_UNSPECIFIED
}

func (x *SubmitSagaResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetSagaStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSagaStatusRequest) Reset() {
	*x = GetSagaStatusRequest{}
	mi := &file_goclaw_v1_saga_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSagaStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSagaStatusRequest) ProtoMessage() {}

func (x *GetSagaStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_saga_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSagaStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSagaStatusRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_saga_proto_rawDescGZIP(), []int{3}
}

func (x *GetSagaStatusRequest) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

type SagaStepResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	ResultJson    []byte                 `protobuf:"bytes,2,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SagaStepResult) Reset() {
	*x = SagaStepResult{}
	mi := &file_goclaw_v1_saga_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SagaStepResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SagaStepResult) ProtoMessage() {}

func (x *SagaStepResult) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_saga_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SagaStepResult.ProtoReflect.Descriptor instead.
func (*SagaStepResult) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_saga_proto_rawDescGZIP(), []int{4}
}

func (x *SagaStepResult) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *SagaStepResult) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

type GetSagaStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SagaId           string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State            SagaState              `protobuf:"varint,3,opt,name=state,proto3,enum=goclaw.v1.SagaState" json:"state,omitempty"`
	CompletedSteps   []string               `protobuf:"bytes,4,rep,name=completed_steps,json=completedSteps,proto3" json:"completed_steps,omitempty"`
	CompensatedSteps []string               `protobuf:"bytes,5,rep,name=compensated_steps,json=compensatedSteps,proto3" json:"compensated_steps,omitempty"`
	FailedStep       string                 `protobuf:"bytes,6,opt,name=failed_step,json=failedStep,proto3" json:"failed_step,omitempty"`
	FailureReason    string                 `protobuf:"bytes,7,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	StepResults      []*SagaStepResult      `protobuf:"bytes,8,rep,name=step_results,json=stepResults,proto3" json:"step_results,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	StartedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSagaStatusResponse) Reset() {
	*x = GetSagaStatusResponse{}
	mi := &file_goclaw_v1_saga_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSagaStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSagaStatusResponse) ProtoMessage() {}

func (x *GetSagaStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_saga_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSagaStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSagaStatusResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_saga_proto_rawDescGZIP(), []int{5}
}

func (x *GetSagaStatusResponse) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *GetSagaStatusResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSagaStatusResponse) GetState() SagaState {
	if x != nil {
		return x.State
	}
	return SagaState_SAGA_STATE_UNSPECIFIED
}

func (x *GetSagaStatusResponse) GetCompletedSteps() []string {
	if x != nil {
		return x.CompletedSteps
	}
	return nil
}

func (x *GetSagaStatusResponse) GetCompensatedSteps() []string {
	if x != nil {
		return x.CompensatedSteps
	}
	return nil
}

func (x *GetSagaStatusResponse) GetFailedStep() string {
	if x != nil {
		return x.FailedStep
	}
	return ""
}

func (x *GetSagaStatusResponse) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *GetSagaStatusResponse) GetStepResults() []*SagaStepResult {
	if x != nil {
		return x.StepResults
	}
	return nil
}

func (x *GetSagaStatusResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetSagaStatusResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetSagaStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *GetSagaStatusResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type ListSagasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	StateFilter   SagaState              `protobuf:"varint,2,opt,name=state_filter,json=stateFilter,proto3,enum=goclaw.v1.SagaState" json:"state_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSagasRequest) Reset() {
	*x = ListSagasRequest{}
	mi := &file_goclaw_v1_saga_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSagasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSagasRequest) ProtoMessage() {}

func (x *ListSagasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_saga_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSagasRequest.ProtoReflect.Descriptor instead.
func (*ListSagasRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_saga_proto_rawDescGZIP(), []int{6}
}

func (x *ListSagasRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListSagasRequest) GetStateFilter() SagaState {
	if x != nil {
		return x.StateFilter
	}
	return SagaState_SAGA_STATE_UNSPECIFIED
}

type SagaSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State         SagaState              `protobuf:"varint,3,opt,name=state,proto3,enum=goclaw.v1.SagaState" json:"state,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SagaSummary) Reset() {
	*x = SagaSummary{}
	mi := &file_goclaw_v1_saga_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SagaSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SagaSummary) ProtoMessage() {}

func (x *SagaSummary) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_saga_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SagaSummary.ProtoReflect.Descriptor instead.
func (*SagaSummary) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_saga_proto_rawDescGZIP(), []int{7}
}

func (x *SagaSummary) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *SagaSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SagaSummary) GetState() SagaState {
	if x != nil {
		return x.State
	}
	return SagaState_SAGA_STATE_UNSPECIFIED
}

func (x *SagaSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SagaSummary) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type ListSagasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sagas         []*SagaSummary         `protobuf:"bytes,1,rep,name=sagas,proto3" json:"sagas,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSagasResponse) Reset() {
	*x = ListSagasResponse{}
	mi := &file_goclaw_v1_saga_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSagasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSagasResponse) ProtoMessage() {}

func (x *ListSagasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_saga_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSagasResponse.ProtoReflect.Descriptor instead.
func (*ListSagasResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_saga_proto_rawDescGZIP(), []int{8}
}

func (x *ListSagasResponse) GetSagas() []*SagaSummary {
	if x != nil {
		return x.Sagas
	}
	return nil
}

func (x *ListSagasResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type CompensateSagaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompensateSagaRequest) Reset() {
	*x = CompensateSagaRequest{}
	mi := &file_goclaw_v1_saga_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompensateSagaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompensateSagaRequest) ProtoMessage() {}

func (x *CompensateSagaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_saga_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompensateSagaRequest.ProtoReflect.Descriptor instead.
func (*CompensateSagaRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_saga_proto_rawDescGZIP(), []int{9}
}

func (x *CompensateSagaRequest) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *CompensateSagaRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CompensateSagaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	State         SagaState              `protobuf:"varint,2,opt,name=state,proto3,enum=goclaw.v1.SagaState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompensateSagaResponse) Reset() {
	*x = CompensateSagaResponse{}
	mi := &file_goclaw_v1_saga_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompensateSagaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompensateSagaResponse) ProtoMessage() {}

func (x *CompensateSagaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_saga_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompensateSagaResponse.ProtoReflect.Descriptor instead.
func (*CompensateSagaResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_saga_proto_rawDescGZIP(), []int{10}
}

func (x *CompensateSagaResponse) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *CompensateSagaResponse) GetState() SagaState {
	if x != nil {
		return x.State
	}
	return SagaState_SAGA_STATE_UNSPECIFIED
}

type WatchSagaRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SagaId         string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	PollIntervalMs int32                  `protobuf:"varint,2,opt,name=poll_interval_ms,json=pollIntervalMs,proto3" json:"poll_interval_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchSagaRequest) Reset() {
	*x = WatchSagaRequest{}
	mi := &file_goclaw_v1_saga_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSagaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSagaRequest) ProtoMessage() {}

func (x *WatchSagaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_saga_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSagaRequest.ProtoReflect.Descriptor instead.
func (*WatchSagaRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_saga_proto_rawDescGZIP(), []int{11}
}

func (x *WatchSagaRequest) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *WatchSagaRequest) GetPollIntervalMs() int32 {
	if x != nil {
		return x.PollIntervalMs
	}
	return 0
}

type WatchSagaEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	State         SagaState              `protobuf:"varint,2,opt,name=state,proto3,enum=goclaw.v1.SagaState" json:"state,omitempty"`
	FailedStep    string                 `protobuf:"bytes,3,opt,name=failed_step,json=failedStep,proto3" json:"failed_step,omitempty"`
	FailureReason string                 `protobuf:"bytes,4,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSagaEvent) Reset() {
	*x = WatchSagaEvent{}
	mi := &file_goclaw_v1_saga_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSagaEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSagaEvent) ProtoMessage() {}

func (x *WatchSagaEvent) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_saga_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSagaEvent.ProtoReflect.Descriptor instead.
func (*WatchSagaEvent) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_saga_proto_rawDescGZIP(), []int{12}
}

func (x *WatchSagaEvent) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *WatchSagaEvent) GetState() SagaState {
	if x != nil {
		return x.State
	}
	return SagaState_SAGA_STATE_UNSPECIFIED
}

func (x *WatchSagaEvent) GetFailedStep() string {
	if x != nil {
		return x.FailedStep
	}
	return ""
}

func (x *WatchSagaEvent) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *WatchSagaEvent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_goclaw_v1_saga_proto protoreflect.FileDescriptor

const file_goclaw_v1_saga_proto_rawDesc = "" +
	"\n" +
	"\x14goclaw/v1/saga.proto\x12\tgoclaw.v1\x1a\x16goclaw/v1/common.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\x01\n" +
	"\x12SagaStepDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x02 \x03(\tR\tdependsOn\x12\x19\n" +
	"\bdelay_ms\x18\x03 \x01(\x05R\adelayMs\x12\x1f\n" +
	"\vshould_fail\x18\x04 \x01(\bR\n" +
	"shouldFail\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x05R\ttimeoutMs\x12/\n" +
	"\x13enable_compensation\x18\x06 \x01(\bR\x12enableCompensation\x12+\n" +
	"\x11skip_compensation\x18\a \x01(\bR\x10skipCompensation\"\x92\x03\n" +
	"\x11SubmitSagaRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\x06policy\x18\x02 \x01(\x0e2!.goclaw.v1.SagaCompensationPolicyR\x06policy\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\x12&\n" +
	"\x0fstep_timeout_ms\x18\x04 \x01(\x05R\rstepTimeoutMs\x12F\n" +
	"\bmetadata\x18\x05 \x03(\v2*.goclaw.v1.SubmitSagaRequest.MetadataEntryR\bmetadata\x12-\n" +
	"\x05input\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x05input\x123\n" +
	"\x05steps\x18\a \x03(\v2\x1d.goclaw.v1.SagaStepDefinitionR\x05steps\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x01\n" +
	"\x12SubmitSagaResponse\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x05state\x18\x03 \x01(\x0e2\x14.goclaw.v1.SagaStateR\x05state\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"/\n" +
	"\x14GetSagaStatusRequest\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\"J\n" +
	"\x0eSagaStepResult\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12\x1f\n" +
	"\vresult_json\x18\x02 \x01(\fR\n" +
	"resultJson\"\xbc\x04\n" +
	"\x15GetSagaStatusResponse\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x05state\x18\x03 \x01(\x0e2\x14.goclaw.v1.SagaStateR\x05state\x12'\n" +
	"\x0fcompleted_steps\x18\x04 \x03(\tR\x0ecompletedSteps\x12+\n" +
	"\x11compensated_steps\x18\x05 \x03(\tR\x10compensatedSteps\x12\x1f\n" +
	"\vfailed_step\x18\x06 \x01(\tR\n" +
	"failedStep\x12%\n" +
	"\x0efailure_reason\x18\a \x01(\tR\rfailureReason\x12<\n" +
	"\fstep_results\x18\b \x03(\v2\x19.goclaw.v1.SagaStepResultR\vstepResults\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"started_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\x89\x01\n" +
	"\x10ListSagasRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.goclaw.v1.PaginationRequestR\n" +
	"pagination\x127\n" +
	"\fstate_filter\x18\x02 \x01(\x0e2\x14.goclaw.v1.SagaStateR\vstateFilter\"\xe0\x01\n" +
	"\vSagaSummary\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x05state\x18\x03 \x01(\x0e2\x14.goclaw.v1.SagaStateR\x05state\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\x80\x01\n" +
	"\x11ListSagasResponse\x12,\n" +
	"\x05sagas\x18\x01 \x03(\v2\x16.goclaw.v1.SagaSummaryR\x05sagas\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.goclaw.v1.PaginationResponseR\n" +
	"pagination\"H\n" +
	"\x15CompensateSagaRequest\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"]\n" +
	"\x16CompensateSagaResponse\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12*\n" +
	"\x05state\x18\x02 \x01(\x0e2\x14.goclaw.v1.SagaStateR\x05state\"U\n" +
	"\x10WatchSagaRequest\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12(\n" +
	"\x10poll_interval_ms\x18\x02 \x01(\x05R\x0epollIntervalMs\"\xd8\x01\n" +
	"\x0eWatchSagaEvent\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12*\n" +
	"\x05state\x18\x02 \x01(\x0e2\x14.goclaw.v1.SagaStateR\x05state\x12\x1f\n" +
	"\vfailed_step\x18\x03 \x01(\tR\n" +
	"failedStep\x12%\n" +
	"\x0efailure_reason\x18\x04 \x01(\tR\rfailureReason\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\x8e\x02\n" +
	"\tSagaState\x12\x1a\n" +
	"\x16SAGA_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SAGA_STATE_CREATED\x10\x01\x12\x16\n" +
	"\x12SAGA_STATE_RUNNING\x10\x02\x12\x18\n" +
	"\x14SAGA_STATE_COMPLETED\x10\x03\x12\x1b\n" +
	"\x17SAGA_STATE_COMPENSATING\x10\x04\x12#\n" +
	"\x1fSAGA_STATE_PENDING_COMPENSATION\x10\x05\x12\x1a\n" +
	"\x16SAGA_STATE_COMPENSATED\x10\x06\x12\"\n" +
	"\x1eSAGA_STATE_COMPENSATION_FAILED\x10\a\x12\x19\n" +
	"\x15SAGA_STATE_RECOVERING\x10\b*\xad\x01\n" +
	"\x16SagaCompensationPolicy\x12(\n" +
	"$SAGA_COMPENSATION_POLICY_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dSAGA_COMPENSATION_POLICY_AUTO\x10\x01\x12#\n" +
	"\x1fSAGA_COMPENSATION_POLICY_MANUAL\x10\x02\x12!\n" +
	"\x1dSAGA_COMPENSATION_POLICY_SKIP\x10\x032\x92\x03\n" +
	"\vSagaService\x12I\n" +
	"\n" +
	"SubmitSaga\x12\x1c.goclaw.v1.SubmitSagaRequest\x1a\x1d.goclaw.v1.SubmitSagaResponse\x12R\n" +
	"\rGetSagaStatus\x12\x1f.goclaw.v1.GetSagaStatusRequest\x1a .goclaw.v1.GetSagaStatusResponse\x12F\n" +
	"\tListSagas\x12\x1b.goclaw.v1.ListSagasRequest\x1a\x1c.goclaw.v1.ListSagasResponse\x12U\n" +
	"\x0eCompensateSaga\x12 .goclaw.v1.CompensateSagaRequest\x1a!.goclaw.v1.CompensateSagaResponse\x12E\n" +
	"\tWatchSaga\x12\x1b.goclaw.v1.WatchSagaRequest\x1a\x19.goclaw.v1.WatchSagaEvent0\x01B.Z,github.com/goclaw/goclaw/pkg/grpc/pb/v1;pbv1b\x06proto3"

var (
	file_goclaw_v1_saga_proto_rawDescOnce sync.Once
	file_goclaw_v1_saga_proto_rawDescData []byte
)

func file_goclaw_v1_saga_proto_rawDescGZIP() []byte {
	file_goclaw_v1_saga_proto_rawDescOnce.Do(func() {
		file_goclaw_v1_saga_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goclaw_v1_saga_proto_rawDesc), len(file_goclaw_v1_saga_proto_rawDesc)))
	})
	return file_goclaw_v1_saga_proto_rawDescData
}

var file_goclaw_v1_saga_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_goclaw_v1_saga_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_goclaw_v1_saga_proto_goTypes = []any{
	(SagaState)(0),                 // 0: goclaw.v1.SagaState
	(SagaCompensationPolicy)(0),    // 1: goclaw.v1.SagaCompensationPolicy
	(*SagaStepDefinition)(nil),     // 2: goclaw.v1.SagaStepDefinition
	(*SubmitSagaRequest)(nil),      // 3: goclaw.v1.SubmitSagaRequest
	(*SubmitSagaResponse)(nil),     // 4: goclaw.v1.SubmitSagaResponse
	(*GetSagaStatusRequest)(nil),   // 5: goclaw.v1.GetSagaStatusRequest
	(*SagaStepResult)(nil),         // 6: goclaw.v1.SagaStepResult
	(*GetSagaStatusResponse)(nil),  // 7: goclaw.v1.GetSagaStatusResponse
	(*ListSagasRequest)(nil),       // 8: goclaw.v1.ListSagasRequest
	(*SagaSummary)(nil),            // 9: goclaw.v1.SagaSummary
	(*ListSagasResponse)(nil),      // 10: goclaw.v1.ListSagasResponse
	(*CompensateSagaRequest)(nil),  // 11: goclaw.v1.CompensateSagaRequest
	(*CompensateSagaResponse)(nil), // 12: goclaw.v1.CompensateSagaResponse
	(*WatchSagaRequest)(nil),       // 13: goclaw.v1.WatchSagaRequest
	(*WatchSagaEvent)(nil),         // 14: goclaw.v1.WatchSagaEvent
	nil,                            // 15: goclaw.v1.SubmitSagaRequest.MetadataEntry
	(*structpb.Struct)(nil),        // 16: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),  // 17: google.protobuf.Timestamp
	(*PaginationRequest)(nil),      // 18: goclaw.v1.PaginationRequest
	(*PaginationResponse)(nil),     // 19: goclaw.v1.PaginationResponse
}
var file_goclaw_v1_saga_proto_depIdxs = []int32{
	1,  // 0: goclaw.v1.SubmitSagaRequest.policy:type_name -> goclaw.v1.SagaCompensationPolicy
	15, // 1: goclaw.v1.SubmitSagaRequest.metadata:type_name -> goclaw.v1.SubmitSagaRequest.MetadataEntry
	16, // 2: goclaw.v1.SubmitSagaRequest.input:type_name -> google.protobuf.Struct
	2,  // 3: goclaw.v1.SubmitSagaRequest.steps:type_name -> goclaw.v1.SagaStepDefinition
	0,  // 4: goclaw.v1.SubmitSagaResponse.state:type_name -> goclaw.v1.SagaState
	17, // 5: goclaw.v1.SubmitSagaResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 6: goclaw.v1.GetSagaStatusResponse.state:type_name -> goclaw.v1.SagaState
	6,  // 7: goclaw.v1.GetSagaStatusResponse.step_results:type_name -> goclaw.v1.SagaStepResult
	17, // 8: goclaw.v1.GetSagaStatusResponse.created_at:type_name -> google.protobuf.Timestamp
	17, // 9: goclaw.v1.GetSagaStatusResponse.updated_at:type_name -> google.protobuf.Timestamp
	17, // 10: goclaw.v1.GetSagaStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	17, // 11: goclaw.v1.GetSagaStatusResponse.completed_at:type_name -> google.protobuf.Timestamp
	18, // 12: goclaw.v1.ListSagasRequest.pagination:type_name -> goclaw.v1.PaginationRequest
	0,  // 13: goclaw.v1.ListSagasRequest.state_filter:type_name -> goclaw.v1.SagaState
	0,  // 14: goclaw.v1.SagaSummary.state:type_name -> goclaw.v1.SagaState
	17, // 15: goclaw.v1.SagaSummary.created_at:type_name -> google.protobuf.Timestamp
	17, // 16: goclaw.v1.SagaSummary.completed_at:type_name -> google.protobuf.Timestamp
	9,  // 17: goclaw.v1.ListSagasResponse.sagas:type_name -> goclaw.v1.SagaSummary
	19, // 18: goclaw.v1.ListSagasResponse.pagination:type_name -> goclaw.v1.PaginationResponse
	0,  // 19: goclaw.v1.CompensateSagaResponse.state:type_name -> goclaw.v1.SagaState
	0,  // 20: goclaw.v1.WatchSagaEvent.state:type_name -> goclaw.v1.SagaState
	17, // 21: goclaw.v1.WatchSagaEvent.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 22: goclaw.v1.SagaService.SubmitSaga:input_type -> goclaw.v1.SubmitSagaRequest
	5,  // 23: goclaw.v1.SagaService.GetSagaStatus:input_type -> goclaw.v1.GetSagaStatusRequest
	8,  // 24: goclaw.v1.SagaService.ListSagas:input_type -> goclaw.v1.ListSagasRequest
	11, // 25: goclaw.v1.SagaService.CompensateSaga:input_type -> goclaw.v1.CompensateSagaRequest
	13, // 26: goclaw.v1.SagaService.WatchSaga:input_type -> goclaw.v1.WatchSagaRequest
	4,  // 27: goclaw.v1.SagaService.SubmitSaga:output_type -> goclaw.v1.SubmitSagaResponse
	7,  // 28: goclaw.v1.SagaService.GetSagaStatus:output_type -> goclaw.v1.GetSagaStatusResponse
	10, // 29: goclaw.v1.SagaService.ListSagas:output_type -> goclaw.v1.ListSagasResponse
	12, // 30: goclaw.v1.SagaService.CompensateSaga:output_type -> goclaw.v1.CompensateSagaResponse
	14, // 31: goclaw.v1.SagaService.WatchSaga:output_type -> goclaw.v1.WatchSagaEvent
	27, // [27:32] is the sub-list for method output_type
	22, // [22:27] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_goclaw_v1_saga_proto_init() }
func file_goclaw_v1_saga_proto_init() {
	if File_goclaw_v1_saga_proto != nil {
		return
	}
	file_goclaw_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goclaw_v1_saga_proto_rawDesc), len(file_goclaw_v1_saga_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goclaw_v1_saga_proto_goTypes,
		DependencyIndexes: file_goclaw_v1_saga_proto_depIdxs,
		EnumInfos:         file_goclaw_v1_saga_proto_enumTypes,
		MessageInfos:      file_goclaw_v1_saga_proto_msgTypes,
	}.Build()
	File_goclaw_v1_saga_proto = out.File
	file_goclaw_v1_saga_proto_goTypes = nil
	file_goclaw_v1_saga_proto_depIdxs = nil
}
