// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.3
// source: goclaw/v1/saga.proto

package pbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SagaService_SubmitSaga_FullMethodName     = "/goclaw.v1.SagaService/SubmitSaga"
	SagaService_GetSagaStatus_FullMethodName  = "/goclaw.v1.SagaService/GetSagaStatus"
	SagaService_ListSagas_FullMethodName      = "/goclaw.v1.SagaService/ListSagas"
	SagaService_CompensateSaga_FullMethodName = "/goclaw.v1.SagaService/CompensateSaga"
	SagaService_WatchSaga_FullMethodName      = "/goclaw.v1.SagaService/WatchSaga"
)

// SagaServiceClient is the client API for SagaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SagaService provides Saga lifecycle operations.
type SagaServiceClient interface {
	SubmitSaga(ctx context.Context, in *SubmitSagaRequest, opts ...grpc.CallOption) (*SubmitSagaResponse, error)
	GetSagaStatus(ctx context.Context, in *GetSagaStatusRequest, opts ...grpc.CallOption) (*GetSagaStatusResponse, error)
	ListSagas(ctx context.Context, in *ListSagasRequest, opts ...grpc.CallOption) (*ListSagasResponse, error)
	CompensateSaga(ctx context.Context, in *CompensateSagaRequest, opts ...grpc.CallOption) (*CompensateSagaResponse, error)
	WatchSaga(ctx context.Context, in *WatchSagaRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchSagaEvent], error)
}

type sagaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSagaServiceClient(cc grpc.ClientConnInterface) SagaServiceClient {
	return &sagaServiceClient{cc}
}

func (c *sagaServiceClient) SubmitSaga(ctx context.Context, in *SubmitSagaRequest, opts ...grpc.CallOption) (*SubmitSagaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitSagaResponse)
	err := c.cc.Invoke(ctx, SagaService_SubmitSaga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sagaServiceClient) GetSagaStatus(ctx context.Context, in *GetSagaStatusRequest, opts ...grpc.CallOption) (*GetSagaStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSagaStatusResponse)
	err := c.cc.Invoke(ctx, SagaService_GetSagaStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sagaServiceClient) ListSagas(ctx context.Context, in *ListSagasRequest, opts ...grpc.CallOption) (*ListSagasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSagasResponse)
	err := c.cc.Invoke(ctx, SagaService_ListSagas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sagaServiceClient) CompensateSaga(ctx context.Context, in *CompensateSagaRequest, opts ...grpc.CallOption) (*CompensateSagaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompensateSagaResponse)
	err := c.cc.Invoke(ctx, SagaService_CompensateSaga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sagaServiceClient) WatchSaga(ctx context.Context, in *WatchSagaRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchSagaEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SagaService_ServiceDesc.Streams[0], SagaService_WatchSaga_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchSagaRequest, WatchSagaEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SagaService_WatchSagaClient = grpc.ServerStreamingClient[WatchSagaEvent]

// SagaServiceServer is the server API for SagaService service.
// All implementations must embed UnimplementedSagaServiceServer
// for forward compatibility.
//
// SagaService provides Saga lifecycle operations.
type SagaServiceServer interface {
	SubmitSaga(context.Context, *SubmitSagaRequest) (*SubmitSagaResponse, error)
	GetSagaStatus(context.Context, *GetSagaStatusRequest) (*GetSagaStatusResponse, error)
	ListSagas(context.Context, *ListSagasRequest) (*ListSagasResponse, error)
	CompensateSaga(context.Context, *CompensateSagaRequest) (*CompensateSagaResponse, error)
	WatchSaga(*WatchSagaRequest, grpc.ServerStreamingServer[WatchSagaEvent]) error
	mustEmbedUnimplementedSagaServiceServer()
}

// UnimplementedSagaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSagaServiceServer struct{}

func (UnimplementedSagaServiceServer) SubmitSaga(context.Context, *SubmitSagaRequest) (*SubmitSagaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitSaga not implemented")
}
func (UnimplementedSagaServiceServer) GetSagaStatus(context.Context, *GetSagaStatusRequest) (*GetSagaStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSagaStatus not implemented")
}
func (UnimplementedSagaServiceServer) ListSagas(context.Context, *ListSagasRequest) (*ListSagasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSagas not implemented")
}
func (UnimplementedSagaServiceServer) CompensateSaga(context.Context, *CompensateSagaRequest) (*CompensateSagaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompensateSaga not implemented")
}
func (UnimplementedSagaServiceServer) WatchSaga(*WatchSagaRequest, grpc.ServerStreamingServer[WatchSagaEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchSaga not implemented")
}
func (UnimplementedSagaServiceServer) mustEmbedUnimplementedSagaServiceServer() {}
func (UnimplementedSagaServiceServer) testEmbeddedByValue()                     {}

// UnsafeSagaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SagaServiceServer will
// result in compilation errors.
type UnsafeSagaServiceServer interface {
	mustEmbedUnimplementedSagaServiceServer()
}

func RegisterSagaServiceServer(s grpc.ServiceRegistrar, srv SagaServiceServer) {
	// If the following call panics, it indicates UnimplementedSagaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SagaService_ServiceDesc, srv)
}

func _SagaService_SubmitSaga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitSagaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaServiceServer).SubmitSaga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaService_SubmitSaga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaServiceServer).SubmitSaga(ctx, req.(*SubmitSagaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SagaService_GetSagaStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSagaStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaServiceServer).GetSagaStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaService_GetSagaStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaServiceServer).GetSagaStatus(ctx, req.(*GetSagaStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SagaService_ListSagas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSagasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaServiceServer).ListSagas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaService_ListSagas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaServiceServer).ListSagas(ctx, req.(*ListSagasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SagaService_CompensateSaga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompensateSagaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaServiceServer).CompensateSaga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaService_CompensateSaga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaServiceServer).CompensateSaga(ctx, req.(*CompensateSagaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SagaService_WatchSaga_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchSagaRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SagaServiceServer).WatchSaga(m, &grpc.GenericServerStream[WatchSagaRequest, WatchSagaEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SagaService_WatchSagaServer = grpc.ServerStreamingServer[WatchSagaEvent]

// SagaService_ServiceDesc is the grpc.ServiceDesc for SagaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SagaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goclaw.v1.SagaService",
	HandlerType: (*SagaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitSaga",
			Handler:    _SagaService_SubmitSaga_Handler,
		},
		{
			MethodName: "GetSagaStatus",
			Handler:    _SagaService_GetSagaStatus_Handler,
		},
		{
			MethodName: "ListSagas",
			Handler:    _SagaService_ListSagas_Handler,
		},
		{
			MethodName: "CompensateSaga",
			Handler:    _SagaService_CompensateSaga_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchSaga",
			Handler:       _SagaService_WatchSaga_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "goclaw/v1/saga.proto",
}
