// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: goclaw/v1/signal.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SignalType defines the kind of signal to send.
type SignalType int32

const (
	SignalType_SIGNAL_TYPE_UNSPECIFIED SignalType = 0
	SignalType_SIGNAL_TYPE_STEER       SignalType = 1
	SignalType_SIGNAL_TYPE_INTERRUPT   SignalType = 2
	SignalType_SIGNAL_TYPE_COLLECT     SignalType = 3
)

// Enum value maps for SignalType.
var (
	SignalType_name = map[int32]string{
		0: "SIGNAL_TYPE_UNSPECIFIED",
		1: "SIGNAL_TYPE_STEER",
		2: "SIGNAL_TYPE_INTERRUPT",
		3: "SIGNAL_TYPE_COLLECT",
	}
	SignalType_value = map[string]int32{
		"SIGNAL_TYPE_UNSPECIFIED": 0,
		"SIGNAL_TYPE_STEER":       1,
		"SIGNAL_TYPE_INTERRUPT":   2,
		"SIGNAL_TYPE_COLLECT":     3,
	}
)

func (x SignalType) Enum() *SignalType {
	p := new(SignalType)
	*p = x
	return p
}

func (x SignalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalType) Descriptor() protoreflect.EnumDescriptor {
	return file_goclaw_v1_signal_proto_enumTypes[0].Descriptor()
}

func (SignalType) Type() protoreflect.EnumType {
	return &file_goclaw_v1_signal_proto_enumTypes[0]
}

func (x SignalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalType.Descriptor instead.
func (SignalType) EnumDescriptor() ([]byte, []int) {
	return file_goclaw_v1_signal_proto_rawDescGZIP(), []int{0}
}

// SignalTaskRequest sends a signal to a task or tasks.
type SignalTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SignalType             `protobuf:"varint,1,opt,name=type,proto3,enum=goclaw.v1.SignalType" json:"type,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskIds       []string               `protobuf:"bytes,3,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Graceful      bool                   `protobuf:"varint,5,opt,name=graceful,proto3" json:"graceful,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,7,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalTaskRequest) Reset() {
	*x = SignalTaskRequest{}
	mi := &file_goclaw_v1_signal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalTaskRequest) ProtoMessage() {}

func (x *SignalTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_signal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalTaskRequest.ProtoReflect.Descriptor instead.
func (*SignalTaskRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_signal_proto_rawDescGZIP(), []int{0}
}

func (x *SignalTaskRequest) GetType() SignalType {
	if x != nil {
		return x.Type
	}
	return SignalType_SIGNAL_TYPE_UNSPECIFIED
}

func (x *SignalTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SignalTaskRequest) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

func (x *SignalTaskRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *SignalTaskRequest) GetGraceful() bool {
	if x != nil {
		return x.Graceful
	}
	return false
}

func (x *SignalTaskRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SignalTaskRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// CollectResult represents a single task result from a collect operation.
type CollectResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ResultData    []byte                 `protobuf:"bytes,2,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectResult) Reset() {
	*x = CollectResult{}
	mi := &file_goclaw_v1_signal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectResult) ProtoMessage() {}

func (x *CollectResult) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_signal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectResult.ProtoReflect.Descriptor instead.
func (*CollectResult) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_signal_proto_rawDescGZIP(), []int{1}
}

func (x *CollectResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CollectResult) GetResultData() []byte {
	if x != nil {
		return x.ResultData
	}
	return nil
}

func (x *CollectResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// SignalTaskResponse reports the result of a signal request.
type SignalTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Results       []*CollectResult       `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalTaskResponse) Reset() {
	*x = SignalTaskResponse{}
	mi := &file_goclaw_v1_signal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalTaskResponse) ProtoMessage() {}

func (x *SignalTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_signal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalTaskResponse.ProtoReflect.Descriptor instead.
func (*SignalTaskResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_signal_proto_rawDescGZIP(), []int{2}
}

func (x *SignalTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SignalTaskResponse) GetResults() []*CollectResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SignalTaskResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_goclaw_v1_signal_proto protoreflect.FileDescriptor

const file_goclaw_v1_signal_proto_rawDesc = "" +
	"\n" +
	"\x16goclaw/v1/signal.proto\x12\tgoclaw.v1\x1a\x16goclaw/v1/common.proto\"\xd2\x02\n" +
	"\x11SignalTaskRequest\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.goclaw.v1.SignalTypeR\x04type\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x19\n" +
	"\btask_ids\x18\x03 \x03(\tR\ataskIds\x12L\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2,.goclaw.v1.SignalTaskRequest.ParametersEntryR\n" +
	"parameters\x12\x1a\n" +
	"\bgraceful\x18\x05 \x01(\bR\bgraceful\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\a \x01(\x03R\ttimeoutMs\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\rCollectResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vresult_data\x18\x02 \x01(\fR\n" +
	"resultData\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x8a\x01\n" +
	"\x12SignalTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\aresults\x18\x02 \x03(\v2\x18.goclaw.v1.CollectResultR\aresults\x12&\n" +
	"\x05error\x18\x03 \x01(\v2\x10.goclaw.v1.ErrorR\x05error*t\n" +
	"\n" +
	"SignalType\x12\x1b\n" +
	"\x17SIGNAL_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SIGNAL_TYPE_STEER\x10\x01\x12\x19\n" +
	"\x15SIGNAL_TYPE_INTERRUPT\x10\x02\x12\x17\n" +
	"\x13SIGNAL_TYPE_COLLECT\x10\x032Z\n" +
	"\rSignalService\x12I\n" +
	"\n" +
	"SignalTask\x12\x1c.goclaw.v1.SignalTaskRequest\x1a\x1d.goclaw.v1.SignalTaskResponseB.Z,github.com/goclaw/goclaw/pkg/grpc/pb/v1;pbv1b\x06proto3"

var (
	file_goclaw_v1_signal_proto_rawDescOnce sync.Once
	file_goclaw_v1_signal_proto_rawDescData []byte
)

func file_goclaw_v1_signal_proto_rawDescGZIP() []byte {
	file_goclaw_v1_signal_proto_rawDescOnce.Do(func() {
		file_goclaw_v1_signal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goclaw_v1_signal_proto_rawDesc), len(file_goclaw_v1_signal_proto_rawDesc)))
	})
	return file_goclaw_v1_signal_proto_rawDescData
}

var file_goclaw_v1_signal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_goclaw_v1_signal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_goclaw_v1_signal_proto_goTypes = []any{
	(SignalType)(0),            // 0: goclaw.v1.SignalType
	(*SignalTaskRequest)(nil),  // 1: goclaw.v1.SignalTaskRequest
	(*CollectResult)(nil),      // 2: goclaw.v1.CollectResult
	(*SignalTaskResponse)(nil), // 3: goclaw.v1.SignalTaskResponse
	nil,                        // 4: goclaw.v1.SignalTaskRequest.ParametersEntry
	(*Error)(nil),              // 5: goclaw.v1.Error
}
var file_goclaw_v1_signal_proto_depIdxs = []int32{
	0, // 0: goclaw.v1.SignalTaskRequest.type:type_name -> goclaw.v1.SignalType
	4, // 1: goclaw.v1.SignalTaskRequest.parameters:type_name -> goclaw.v1.SignalTaskRequest.ParametersEntry
	2, // 2: goclaw.v1.SignalTaskResponse.results:type_name -> goclaw.v1.CollectResult
	5, // 3: goclaw.v1.SignalTaskResponse.error:type_name -> goclaw.v1.Error
	1, // 4: goclaw.v1.SignalService.SignalTask:input_type -> goclaw.v1.SignalTaskRequest
	3, // 5: goclaw.v1.SignalService.SignalTask:output_type -> goclaw.v1.SignalTaskResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_goclaw_v1_signal_proto_init() }
func file_goclaw_v1_signal_proto_init() {
	if File_goclaw_v1_signal_proto != nil {
		return
	}
	file_goclaw_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goclaw_v1_signal_proto_rawDesc), len(file_goclaw_v1_signal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goclaw_v1_signal_proto_goTypes,
		DependencyIndexes: file_goclaw_v1_signal_proto_depIdxs,
		EnumInfos:         file_goclaw_v1_signal_proto_enumTypes,
		MessageInfos:      file_goclaw_v1_signal_proto_msgTypes,
	}.Build()
	File_goclaw_v1_signal_proto = out.File
	file_goclaw_v1_signal_proto_goTypes = nil
	file_goclaw_v1_signal_proto_depIdxs = nil
}
