// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: goclaw/v1/streaming.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Log level enum
type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARN        LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_WARN",
		4: "LOG_LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_WARN":        3,
		"LOG_LEVEL_ERROR":       4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_goclaw_v1_streaming_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_goclaw_v1_streaming_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_goclaw_v1_streaming_proto_rawDescGZIP(), []int{0}
}

// Watch workflow request
type WatchWorkflowRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId         string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	ResumeFromSequence int64                  `protobuf:"varint,2,opt,name=resume_from_sequence,json=resumeFromSequence,proto3" json:"resume_from_sequence,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WatchWorkflowRequest) Reset() {
	*x = WatchWorkflowRequest{}
	mi := &file_goclaw_v1_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchWorkflowRequest) ProtoMessage() {}

func (x *WatchWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchWorkflowRequest.ProtoReflect.Descriptor instead.
func (*WatchWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *WatchWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WatchWorkflowRequest) GetResumeFromSequence() int64 {
	if x != nil {
		return x.ResumeFromSequence
	}
	return 0
}

// Workflow status update
type WorkflowStatusUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int64                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	WorkflowId     string                 `protobuf:"bytes,3,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Status         WorkflowStatus         `protobuf:"varint,4,opt,name=status,proto3,enum=goclaw.v1.WorkflowStatus" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Error          *Error                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkflowStatusUpdate) Reset() {
	*x = WorkflowStatusUpdate{}
	mi := &file_goclaw_v1_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStatusUpdate) ProtoMessage() {}

func (x *WorkflowStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStatusUpdate.ProtoReflect.Descriptor instead.
func (*WorkflowStatusUpdate) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowStatusUpdate) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *WorkflowStatusUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *WorkflowStatusUpdate) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowStatusUpdate) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *WorkflowStatusUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkflowStatusUpdate) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Watch tasks request
type WatchTasksRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId         string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	TaskIds            []string               `protobuf:"bytes,2,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	TerminalOnly       bool                   `protobuf:"varint,3,opt,name=terminal_only,json=terminalOnly,proto3" json:"terminal_only,omitempty"`
	ResumeFromSequence int64                  `protobuf:"varint,4,opt,name=resume_from_sequence,json=resumeFromSequence,proto3" json:"resume_from_sequence,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WatchTasksRequest) Reset() {
	*x = WatchTasksRequest{}
	mi := &file_goclaw_v1_streaming_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTasksRequest) ProtoMessage() {}

func (x *WatchTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_streaming_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTasksRequest.ProtoReflect.Descriptor instead.
func (*WatchTasksRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_streaming_proto_rawDescGZIP(), []int{2}
}

func (x *WatchTasksRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WatchTasksRequest) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

func (x *WatchTasksRequest) GetTerminalOnly() bool {
	if x != nil {
		return x.TerminalOnly
	}
	return false
}

func (x *WatchTasksRequest) GetResumeFromSequence() int64 {
	if x != nil {
		return x.ResumeFromSequence
	}
	return 0
}

// Task progress update
type TaskProgressUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber  int64                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	WorkflowId      string                 `protobuf:"bytes,3,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	TaskId          string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status          TaskStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=goclaw.v1.TaskStatus" json:"status,omitempty"`
	ProgressPercent int32                  `protobuf:"varint,6,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	Message         string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	Error           *Error                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskProgressUpdate) Reset() {
	*x = TaskProgressUpdate{}
	mi := &file_goclaw_v1_streaming_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProgressUpdate) ProtoMessage() {}

func (x *TaskProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_streaming_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProgressUpdate.ProtoReflect.Descriptor instead.
func (*TaskProgressUpdate) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_streaming_proto_rawDescGZIP(), []int{3}
}

func (x *TaskProgressUpdate) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *TaskProgressUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TaskProgressUpdate) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *TaskProgressUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskProgressUpdate) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskProgressUpdate) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *TaskProgressUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskProgressUpdate) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Log stream request (client to server)
type LogStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	MinLevel      LogLevel               `protobuf:"varint,2,opt,name=min_level,json=minLevel,proto3,enum=goclaw.v1.LogLevel" json:"min_level,omitempty"`
	TaskIds       []string               `protobuf:"bytes,3,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStreamRequest) Reset() {
	*x = LogStreamRequest{}
	mi := &file_goclaw_v1_streaming_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamRequest) ProtoMessage() {}

func (x *LogStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_streaming_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamRequest.ProtoReflect.Descriptor instead.
func (*LogStreamRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_streaming_proto_rawDescGZIP(), []int{4}
}

func (x *LogStreamRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *LogStreamRequest) GetMinLevel() LogLevel {
	if x != nil {
		return x.MinLevel
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogStreamRequest) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

// Log entry
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         LogLevel               `protobuf:"varint,2,opt,name=level,proto3,enum=goclaw.v1.LogLevel" json:"level,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,3,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_goclaw_v1_streaming_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_streaming_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_streaming_proto_rawDescGZIP(), []int{5}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogEntry) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *LogEntry) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Log stream response (server to client)
type LogStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStreamResponse) Reset() {
	*x = LogStreamResponse{}
	mi := &file_goclaw_v1_streaming_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamResponse) ProtoMessage() {}

func (x *LogStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_streaming_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamResponse.ProtoReflect.Descriptor instead.
func (*LogStreamResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_streaming_proto_rawDescGZIP(), []int{6}
}

func (x *LogStreamResponse) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *LogStreamResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_goclaw_v1_streaming_proto protoreflect.FileDescriptor

const file_goclaw_v1_streaming_proto_rawDesc = "" +
	"\n" +
	"\x19goclaw/v1/streaming.proto\x12\tgoclaw.v1\x1a\x16goclaw/v1/common.proto\x1a\x18goclaw/v1/workflow.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"i\n" +
	"\x14WatchWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x120\n" +
	"\x14resume_from_sequence\x18\x02 \x01(\x03R\x12resumeFromSequence\"\x8f\x02\n" +
	"\x14WorkflowStatusUpdate\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x03R\x0esequenceNumber\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vworkflow_id\x18\x03 \x01(\tR\n" +
	"workflowId\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.goclaw.v1.WorkflowStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12&\n" +
	"\x05error\x18\x06 \x01(\v2\x10.goclaw.v1.ErrorR\x05error\"\xa6\x01\n" +
	"\x11WatchTasksRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x19\n" +
	"\btask_ids\x18\x02 \x03(\tR\ataskIds\x12#\n" +
	"\rterminal_only\x18\x03 \x01(\bR\fterminalOnly\x120\n" +
	"\x14resume_from_sequence\x18\x04 \x01(\x03R\x12resumeFromSequence\"\xcd\x02\n" +
	"\x12TaskProgressUpdate\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x03R\x0esequenceNumber\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vworkflow_id\x18\x03 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.goclaw.v1.TaskStatusR\x06status\x12)\n" +
	"\x10progress_percent\x18\x06 \x01(\x05R\x0fprogressPercent\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12&\n" +
	"\x05error\x18\b \x01(\v2\x10.goclaw.v1.ErrorR\x05error\"\x80\x01\n" +
	"\x10LogStreamRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x120\n" +
	"\tmin_level\x18\x02 \x01(\x0e2\x13.goclaw.v1.LogLevelR\bminLevel\x12\x19\n" +
	"\btask_ids\x18\x03 \x03(\tR\ataskIds\"\xb7\x02\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12)\n" +
	"\x05level\x18\x02 \x01(\x0e2\x13.goclaw.v1.LogLevelR\x05level\x12\x1f\n" +
	"\vworkflow_id\x18\x03 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x127\n" +
	"\x06fields\x18\x06 \x03(\v2\x1f.goclaw.v1.LogEntry.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x11LogStreamResponse\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.goclaw.v1.LogEntryR\aentries\x12&\n" +
	"\x05error\x18\x02 \x01(\v2\x10.goclaw.v1.ErrorR\x05error*w\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x03\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x042\x81\x02\n" +
	"\x10StreamingService\x12S\n" +
	"\rWatchWorkflow\x12\x1f.goclaw.v1.WatchWorkflowRequest\x1a\x1f.goclaw.v1.WorkflowStatusUpdate0\x01\x12K\n" +
	"\n" +
	"WatchTasks\x12\x1c.goclaw.v1.WatchTasksRequest\x1a\x1d.goclaw.v1.TaskProgressUpdate0\x01\x12K\n" +
	"\n" +
	"StreamLogs\x12\x1b.goclaw.v1.LogStreamRequest\x1a\x1c.goclaw.v1.LogStreamResponse(\x010\x01B.Z,github.com/goclaw/goclaw/pkg/grpc/pb/v1;pbv1b\x06proto3"

var (
	file_goclaw_v1_streaming_proto_rawDescOnce sync.Once
	file_goclaw_v1_streaming_proto_rawDescData []byte
)

func file_goclaw_v1_streaming_proto_rawDescGZIP() []byte {
	file_goclaw_v1_streaming_proto_rawDescOnce.Do(func() {
		file_goclaw_v1_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goclaw_v1_streaming_proto_rawDesc), len(file_goclaw_v1_streaming_proto_rawDesc)))
	})
	return file_goclaw_v1_streaming_proto_rawDescData
}

var file_goclaw_v1_streaming_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_goclaw_v1_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_goclaw_v1_streaming_proto_goTypes = []any{
	(LogLevel)(0),                 // 0: goclaw.v1.LogLevel
	(*WatchWorkflowRequest)(nil),  // 1: goclaw.v1.WatchWorkflowRequest
	(*WorkflowStatusUpdate)(nil),  // 2: goclaw.v1.WorkflowStatusUpdate
	(*WatchTasksRequest)(nil),     // 3: goclaw.v1.WatchTasksRequest
	(*TaskProgressUpdate)(nil),    // 4: goclaw.v1.TaskProgressUpdate
	(*LogStreamRequest)(nil),      // 5: goclaw.v1.LogStreamRequest
	(*LogEntry)(nil),              // 6: goclaw.v1.LogEntry
	(*LogStreamResponse)(nil),     // 7: goclaw.v1.LogStreamResponse
	nil,                           // 8: goclaw.v1.LogEntry.FieldsEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(WorkflowStatus)(0),           // 10: goclaw.v1.WorkflowStatus
	(*Error)(nil),                 // 11: goclaw.v1.Error
	(TaskStatus)(0),               // 12: goclaw.v1.TaskStatus
}
var file_goclaw_v1_streaming_proto_depIdxs = []int32{
	9,  // 0: goclaw.v1.WorkflowStatusUpdate.timestamp:type_name -> google.protobuf.Timestamp
	10, // 1: goclaw.v1.WorkflowStatusUpdate.status:type_name -> goclaw.v1.WorkflowStatus
	11, // 2: goclaw.v1.WorkflowStatusUpdate.error:type_name -> goclaw.v1.Error
	9,  // 3: goclaw.v1.TaskProgressUpdate.timestamp:type_name -> google.protobuf.Timestamp
	12, // 4: goclaw.v1.TaskProgressUpdate.status:type_name -> goclaw.v1.TaskStatus
	11, // 5: goclaw.v1.TaskProgressUpdate.error:type_name -> goclaw.v1.Error
	0,  // 6: goclaw.v1.LogStreamRequest.min_level:type_name -> goclaw.v1.LogLevel
	9,  // 7: goclaw.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 8: goclaw.v1.LogEntry.level:type_name -> goclaw.v1.LogLevel
	8,  // 9: goclaw.v1.LogEntry.fields:type_name -> goclaw.v1.LogEntry.FieldsEntry
	6,  // 10: goclaw.v1.LogStreamResponse.entries:type_name -> goclaw.v1.LogEntry
	11, // 11: goclaw.v1.LogStreamResponse.error:type_name -> goclaw.v1.Error
	1,  // 12: goclaw.v1.StreamingService.WatchWorkflow:input_type -> goclaw.v1.WatchWorkflowRequest
	3,  // 13: goclaw.v1.StreamingService.WatchTasks:input_type -> goclaw.v1.WatchTasksRequest
	5,  // 14: goclaw.v1.StreamingService.StreamLogs:input_type -> goclaw.v1.LogStreamRequest
	2,  // 15: goclaw.v1.StreamingService.WatchWorkflow:output_type -> goclaw.v1.WorkflowStatusUpdate
	4,  // 16: goclaw.v1.StreamingService.WatchTasks:output_type -> goclaw.v1.TaskProgressUpdate
	7,  // 17: goclaw.v1.StreamingService.StreamLogs:output_type -> goclaw.v1.LogStreamResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_goclaw_v1_streaming_proto_init() }
func file_goclaw_v1_streaming_proto_init() {
	if File_goclaw_v1_streaming_proto != nil {
		return
	}
	file_goclaw_v1_common_proto_init()
	file_goclaw_v1_workflow_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goclaw_v1_streaming_proto_rawDesc), len(file_goclaw_v1_streaming_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goclaw_v1_streaming_proto_goTypes,
		DependencyIndexes: file_goclaw_v1_streaming_proto_depIdxs,
		EnumInfos:         file_goclaw_v1_streaming_proto_enumTypes,
		MessageInfos:      file_goclaw_v1_streaming_proto_msgTypes,
	}.Build()
	File_goclaw_v1_streaming_proto = out.File
	file_goclaw_v1_streaming_proto_goTypes = nil
	file_goclaw_v1_streaming_proto_depIdxs = nil
}
