// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.3
// source: goclaw/v1/streaming.proto

package pbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamingService_WatchWorkflow_FullMethodName = "/goclaw.v1.StreamingService/WatchWorkflow"
	StreamingService_WatchTasks_FullMethodName    = "/goclaw.v1.StreamingService/WatchTasks"
	StreamingService_StreamLogs_FullMethodName    = "/goclaw.v1.StreamingService/StreamLogs"
)

// StreamingServiceClient is the client API for StreamingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StreamingService provides real-time streaming operations
type StreamingServiceClient interface {
	WatchWorkflow(ctx context.Context, in *WatchWorkflowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkflowStatusUpdate], error)
	WatchTasks(ctx context.Context, in *WatchTasksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgressUpdate], error)
	StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LogStreamRequest, LogStreamResponse], error)
}

type streamingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamingServiceClient(cc grpc.ClientConnInterface) StreamingServiceClient {
	return &streamingServiceClient{cc}
}

func (c *streamingServiceClient) WatchWorkflow(ctx context.Context, in *WatchWorkflowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkflowStatusUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamingService_ServiceDesc.Streams[0], StreamingService_WatchWorkflow_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchWorkflowRequest, WorkflowStatusUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingService_WatchWorkflowClient = grpc.ServerStreamingClient[WorkflowStatusUpdate]

func (c *streamingServiceClient) WatchTasks(ctx context.Context, in *WatchTasksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgressUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamingService_ServiceDesc.Streams[1], StreamingService_WatchTasks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchTasksRequest, TaskProgressUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingService_WatchTasksClient = grpc.ServerStreamingClient[TaskProgressUpdate]

func (c *streamingServiceClient) StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LogStreamRequest, LogStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamingService_ServiceDesc.Streams[2], StreamingService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogStreamRequest, LogStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingService_StreamLogsClient = grpc.BidiStreamingClient[LogStreamRequest, LogStreamResponse]

// StreamingServiceServer is the server API for StreamingService service.
// All implementations must embed UnimplementedStreamingServiceServer
// for forward compatibility.
//
// StreamingService provides real-time streaming operations
type StreamingServiceServer interface {
	WatchWorkflow(*WatchWorkflowRequest, grpc.ServerStreamingServer[WorkflowStatusUpdate]) error
	WatchTasks(*WatchTasksRequest, grpc.ServerStreamingServer[TaskProgressUpdate]) error
	StreamLogs(grpc.BidiStreamingServer[LogStreamRequest, LogStreamResponse]) error
	mustEmbedUnimplementedStreamingServiceServer()
}

// UnimplementedStreamingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamingServiceServer struct{}

func (UnimplementedStreamingServiceServer) WatchWorkflow(*WatchWorkflowRequest, grpc.ServerStreamingServer[WorkflowStatusUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchWorkflow not implemented")
}
func (UnimplementedStreamingServiceServer) WatchTasks(*WatchTasksRequest, grpc.ServerStreamingServer[TaskProgressUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchTasks not implemented")
}
func (UnimplementedStreamingServiceServer) StreamLogs(grpc.BidiStreamingServer[LogStreamRequest, LogStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedStreamingServiceServer) mustEmbedUnimplementedStreamingServiceServer() {}
func (UnimplementedStreamingServiceServer) testEmbeddedByValue()                          {}

// UnsafeStreamingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamingServiceServer will
// result in compilation errors.
type UnsafeStreamingServiceServer interface {
	mustEmbedUnimplementedStreamingServiceServer()
}

func RegisterStreamingServiceServer(s grpc.ServiceRegistrar, srv StreamingServiceServer) {
	// If the following call panics, it indicates UnimplementedStreamingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamingService_ServiceDesc, srv)
}

func _StreamingService_WatchWorkflow_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchWorkflowRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamingServiceServer).WatchWorkflow(m, &grpc.GenericServerStream[WatchWorkflowRequest, WorkflowStatusUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingService_WatchWorkflowServer = grpc.ServerStreamingServer[WorkflowStatusUpdate]

func _StreamingService_WatchTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchTasksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamingServiceServer).WatchTasks(m, &grpc.GenericServerStream[WatchTasksRequest, TaskProgressUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingService_WatchTasksServer = grpc.ServerStreamingServer[TaskProgressUpdate]

func _StreamingService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamingServiceServer).StreamLogs(&grpc.GenericServerStream[LogStreamRequest, LogStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingService_StreamLogsServer = grpc.BidiStreamingServer[LogStreamRequest, LogStreamResponse]

// StreamingService_ServiceDesc is the grpc.ServiceDesc for StreamingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goclaw.v1.StreamingService",
	HandlerType: (*StreamingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchWorkflow",
			Handler:       _StreamingService_WatchWorkflow_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchTasks",
			Handler:       _StreamingService_WatchTasks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _StreamingService_StreamLogs_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "goclaw/v1/streaming.proto",
}
