// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: goclaw/v1/workflow.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Workflow status enum
type WorkflowStatus int32

const (
	WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED WorkflowStatus = 0
	WorkflowStatus_WORKFLOW_STATUS_PENDING     WorkflowStatus = 1
	WorkflowStatus_WORKFLOW_STATUS_RUNNING     WorkflowStatus = 2
	WorkflowStatus_WORKFLOW_STATUS_COMPLETED   WorkflowStatus = 3
	WorkflowStatus_WORKFLOW_STATUS_FAILED      WorkflowStatus = 4
	WorkflowStatus_WORKFLOW_STATUS_CANCELLED   WorkflowStatus = 5
)

// Enum value maps for WorkflowStatus.
var (
	WorkflowStatus_name = map[int32]string{
		0: "WORKFLOW_STATUS_UNSPECIFIED",
		1: "WORKFLOW_STATUS_PENDING",
		2: "WORKFLOW_STATUS_RUNNING",
		3: "WORKFLOW_STATUS_COMPLETED",
		4: "WORKFLOW_STATUS_FAILED",
		5: "WORKFLOW_STATUS_CANCELLED",
	}
	WorkflowStatus_value = map[string]int32{
		"WORKFLOW_STATUS_UNSPECIFIED": 0,
		"WORKFLOW_STATUS_PENDING":     1,
		"WORKFLOW_STATUS_RUNNING":     2,
		"WORKFLOW_STATUS_COMPLETED":   3,
		"WORKFLOW_STATUS_FAILED":      4,
		"WORKFLOW_STATUS_CANCELLED":   5,
	}
)

func (x WorkflowStatus) Enum() *WorkflowStatus {
	p := new(WorkflowStatus)
	*p = x
	return p
}

func (x WorkflowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_goclaw_v1_workflow_proto_enumTypes[0].Descriptor()
}

func (WorkflowStatus) Type() protoreflect.EnumType {
	return &file_goclaw_v1_workflow_proto_enumTypes[0]
}

func (x WorkflowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowStatus.Descriptor instead.
func (WorkflowStatus) EnumDescriptor() ([]byte, []int) {
	return file_goclaw_v1_workflow_proto_rawDescGZIP(), []int{0}
}

// Task status enum
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING     TaskStatus = 1
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 2
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 3
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 4
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 5
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_PENDING",
		2: "TASK_STATUS_RUNNING",
		3: "TASK_STATUS_COMPLETED",
		4: "TASK_STATUS_FAILED",
		5: "TASK_STATUS_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_PENDING":     1,
		"TASK_STATUS_RUNNING":     2,
		"TASK_STATUS_COMPLETED":   3,
		"TASK_STATUS_FAILED":      4,
		"TASK_STATUS_CANCELLED":   5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_goclaw_v1_workflow_proto_enumTypes[1].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_goclaw_v1_workflow_proto_enumTypes[1]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_goclaw_v1_workflow_proto_rawDescGZIP(), []int{1}
}

// Task definition
type TaskDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Dependencies  []string               `protobuf:"bytes,3,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDefinition) Reset() {
	*x = TaskDefinition{}
	mi := &file_goclaw_v1_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDefinition) ProtoMessage() {}

func (x *TaskDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDefinition.ProtoReflect.Descriptor instead.
func (*TaskDefinition) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *TaskDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskDefinition) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *TaskDefinition) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Submit workflow request
type SubmitWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tasks         []*TaskDefinition      `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWorkflowRequest) Reset() {
	*x = SubmitWorkflowRequest{}
	mi := &file_goclaw_v1_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWorkflowRequest) ProtoMessage() {}

func (x *SubmitWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWorkflowRequest.ProtoReflect.Descriptor instead.
func (*SubmitWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitWorkflowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubmitWorkflowRequest) GetTasks() []*TaskDefinition {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *SubmitWorkflowRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Submit workflow response
type SubmitWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWorkflowResponse) Reset() {
	*x = SubmitWorkflowResponse{}
	mi := &file_goclaw_v1_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWorkflowResponse) ProtoMessage() {}

func (x *SubmitWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWorkflowResponse.ProtoReflect.Descriptor instead.
func (*SubmitWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitWorkflowResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *SubmitWorkflowResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// List workflows request
type ListWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	StatusFilter  WorkflowStatus         `protobuf:"varint,2,opt,name=status_filter,json=statusFilter,proto3,enum=goclaw.v1.WorkflowStatus" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsRequest) Reset() {
	*x = ListWorkflowsRequest{}
	mi := &file_goclaw_v1_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsRequest) ProtoMessage() {}

func (x *ListWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *ListWorkflowsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListWorkflowsRequest) GetStatusFilter() WorkflowStatus {
	if x != nil {
		return x.StatusFilter
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

// Workflow summary
type WorkflowSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        WorkflowStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=goclaw.v1.WorkflowStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowSummary) Reset() {
	*x = WorkflowSummary{}
	mi := &file_goclaw_v1_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowSummary) ProtoMessage() {}

func (x *WorkflowSummary) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowSummary.ProtoReflect.Descriptor instead.
func (*WorkflowSummary) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *WorkflowSummary) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowSummary) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *WorkflowSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WorkflowSummary) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// List workflows response
type ListWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*WorkflowSummary     `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsResponse) Reset() {
	*x = ListWorkflowsResponse{}
	mi := &file_goclaw_v1_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsResponse) ProtoMessage() {}

func (x *ListWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *ListWorkflowsResponse) GetWorkflows() []*WorkflowSummary {
	if x != nil {
		return x.Workflows
	}
	return nil
}

func (x *ListWorkflowsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListWorkflowsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Get workflow status request
type GetWorkflowStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowStatusRequest) Reset() {
	*x = GetWorkflowStatusRequest{}
	mi := &file_goclaw_v1_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowStatusRequest) ProtoMessage() {}

func (x *GetWorkflowStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowStatusRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowStatusRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *GetWorkflowStatusRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

// Task status detail
type TaskStatusDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        TaskStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=goclaw.v1.TaskStatus" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusDetail) Reset() {
	*x = TaskStatusDetail{}
	mi := &file_goclaw_v1_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusDetail) ProtoMessage() {}

func (x *TaskStatusDetail) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusDetail.ProtoReflect.Descriptor instead.
func (*TaskStatusDetail) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *TaskStatusDetail) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatusDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskStatusDetail) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskStatusDetail) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *TaskStatusDetail) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *TaskStatusDetail) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Get workflow status response
type GetWorkflowStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        WorkflowStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=goclaw.v1.WorkflowStatus" json:"status,omitempty"`
	Tasks         []*TaskStatusDetail    `protobuf:"bytes,4,rep,name=tasks,proto3" json:"tasks,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Error         *Error                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowStatusResponse) Reset() {
	*x = GetWorkflowStatusResponse{}
	mi := &file_goclaw_v1_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowStatusResponse) ProtoMessage() {}

func (x *GetWorkflowStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowStatusResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowStatusResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *GetWorkflowStatusResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *GetWorkflowStatusResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetWorkflowStatusResponse) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *GetWorkflowStatusResponse) GetTasks() []*TaskStatusDetail {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *GetWorkflowStatusResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetWorkflowStatusResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetWorkflowStatusResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Cancel workflow request
type CancelWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflowRequest) Reset() {
	*x = CancelWorkflowRequest{}
	mi := &file_goclaw_v1_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowRequest) ProtoMessage() {}

func (x *CancelWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CancelWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_workflow_proto_rawDescGZIP(), []int{9}
}

func (x *CancelWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *CancelWorkflowRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// Cancel workflow response
type CancelWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflowResponse) Reset() {
	*x = CancelWorkflowResponse{}
	mi := &file_goclaw_v1_workflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowResponse) ProtoMessage() {}

func (x *CancelWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_workflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowResponse.ProtoReflect.Descriptor instead.
func (*CancelWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_workflow_proto_rawDescGZIP(), []int{10}
}

func (x *CancelWorkflowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelWorkflowResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Get task result request
type GetTaskResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResultRequest) Reset() {
	*x = GetTaskResultRequest{}
	mi := &file_goclaw_v1_workflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResultRequest) ProtoMessage() {}

func (x *GetTaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_workflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResultRequest.ProtoReflect.Descriptor instead.
func (*GetTaskResultRequest) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_workflow_proto_rawDescGZIP(), []int{11}
}

func (x *GetTaskResultRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *GetTaskResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// Get task result response
type GetTaskResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=goclaw.v1.TaskStatus" json:"status,omitempty"`
	ResultData    []byte                 `protobuf:"bytes,3,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Error         *Error                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResultResponse) Reset() {
	*x = GetTaskResultResponse{}
	mi := &file_goclaw_v1_workflow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResultResponse) ProtoMessage() {}

func (x *GetTaskResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goclaw_v1_workflow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResultResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResultResponse) Descriptor() ([]byte, []int) {
	return file_goclaw_v1_workflow_proto_rawDescGZIP(), []int{12}
}

func (x *GetTaskResultResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskResultResponse) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *GetTaskResultResponse) GetResultData() []byte {
	if x != nil {
		return x.ResultData
	}
	return nil
}

func (x *GetTaskResultResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetTaskResultResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_goclaw_v1_workflow_proto protoreflect.FileDescriptor

const file_goclaw_v1_workflow_proto_rawDesc = "" +
	"\n" +
	"\x18goclaw/v1/workflow.proto\x12\tgoclaw.v1\x1a\x16goclaw/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x01\n" +
	"\x0eTaskDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\fdependencies\x18\x03 \x03(\tR\fdependencies\x12C\n" +
	"\bmetadata\x18\x04 \x03(\v2'.goclaw.v1.TaskDefinition.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe5\x01\n" +
	"\x15SubmitWorkflowRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x05tasks\x18\x02 \x03(\v2\x19.goclaw.v1.TaskDefinitionR\x05tasks\x12J\n" +
	"\bmetadata\x18\x03 \x03(\v2..goclaw.v1.SubmitWorkflowRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\x16SubmitWorkflowResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12&\n" +
	"\x05error\x18\x02 \x01(\v2\x10.goclaw.v1.ErrorR\x05error\"\x94\x01\n" +
	"\x14ListWorkflowsRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.goclaw.v1.PaginationRequestR\n" +
	"pagination\x12>\n" +
	"\rstatus_filter\x18\x02 \x01(\x0e2\x19.goclaw.v1.WorkflowStatusR\fstatusFilter\"\xef\x01\n" +
	"\x0fWorkflowSummary\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.goclaw.v1.WorkflowStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb8\x01\n" +
	"\x15ListWorkflowsResponse\x128\n" +
	"\tworkflows\x18\x01 \x03(\v2\x1a.goclaw.v1.WorkflowSummaryR\tworkflows\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.goclaw.v1.PaginationResponseR\n" +
	"pagination\x12&\n" +
	"\x05error\x18\x03 \x01(\v2\x10.goclaw.v1.ErrorR\x05error\";\n" +
	"\x18GetWorkflowStatusRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"\x8d\x02\n" +
	"\x10TaskStatusDetail\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.goclaw.v1.TaskStatusR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\xd4\x02\n" +
	"\x19GetWorkflowStatusResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.goclaw.v1.WorkflowStatusR\x06status\x121\n" +
	"\x05tasks\x18\x04 \x03(\v2\x1b.goclaw.v1.TaskStatusDetailR\x05tasks\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12&\n" +
	"\x05error\x18\a \x01(\v2\x10.goclaw.v1.ErrorR\x05error\"N\n" +
	"\x15CancelWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"Z\n" +
	"\x16CancelWorkflowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x05error\x18\x02 \x01(\v2\x10.goclaw.v1.ErrorR\x05error\"P\n" +
	"\x14GetTaskResultRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"\xcd\x01\n" +
	"\x15GetTaskResultResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.goclaw.v1.TaskStatusR\x06status\x12\x1f\n" +
	"\vresult_data\x18\x03 \x01(\fR\n" +
	"resultData\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12&\n" +
	"\x05error\x18\x05 \x01(\v2\x10.goclaw.v1.ErrorR\x05error*\xc5\x01\n" +
	"\x0eWorkflowStatus\x12\x1f\n" +
	"\x1bWORKFLOW_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_RUNNING\x10\x02\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_COMPLETED\x10\x03\x12\x1a\n" +
	"\x16WORKFLOW_STATUS_FAILED\x10\x04\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_CANCELLED\x10\x05*\xa9\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x02\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x03\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x04\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\x052\xc7\x03\n" +
	"\x0fWorkflowService\x12U\n" +
	"\x0eSubmitWorkflow\x12 .goclaw.v1.SubmitWorkflowRequest\x1a!.goclaw.v1.SubmitWorkflowResponse\x12R\n" +
	"\rListWorkflows\x12\x1f.goclaw.v1.ListWorkflowsRequest\x1a .goclaw.v1.ListWorkflowsResponse\x12^\n" +
	"\x11GetWorkflowStatus\x12#.goclaw.v1.GetWorkflowStatusRequest\x1a$.goclaw.v1.GetWorkflowStatusResponse\x12U\n" +
	"\x0eCancelWorkflow\x12 .goclaw.v1.CancelWorkflowRequest\x1a!.goclaw.v1.CancelWorkflowResponse\x12R\n" +
	"\rGetTaskResult\x12\x1f.goclaw.v1.GetTaskResultRequest\x1a .goclaw.v1.GetTaskResultResponseB.Z,github.com/goclaw/goclaw/pkg/grpc/pb/v1;pbv1b\x06proto3"

var (
	file_goclaw_v1_workflow_proto_rawDescOnce sync.Once
	file_goclaw_v1_workflow_proto_rawDescData []byte
)

func file_goclaw_v1_workflow_proto_rawDescGZIP() []byte {
	file_goclaw_v1_workflow_proto_rawDescOnce.Do(func() {
		file_goclaw_v1_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goclaw_v1_workflow_proto_rawDesc), len(file_goclaw_v1_workflow_proto_rawDesc)))
	})
	return file_goclaw_v1_workflow_proto_rawDescData
}

var file_goclaw_v1_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_goclaw_v1_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_goclaw_v1_workflow_proto_goTypes = []any{
	(WorkflowStatus)(0),               // 0: goclaw.v1.WorkflowStatus
	(TaskStatus)(0),                   // 1: goclaw.v1.TaskStatus
	(*TaskDefinition)(nil),            // 2: goclaw.v1.TaskDefinition
	(*SubmitWorkflowRequest)(nil),     // 3: goclaw.v1.SubmitWorkflowRequest
	(*SubmitWorkflowResponse)(nil),    // 4: goclaw.v1.SubmitWorkflowResponse
	(*ListWorkflowsRequest)(nil),      // 5: goclaw.v1.ListWorkflowsRequest
	(*WorkflowSummary)(nil),           // 6: goclaw.v1.WorkflowSummary
	(*ListWorkflowsResponse)(nil),     // 7: goclaw.v1.ListWorkflowsResponse
	(*GetWorkflowStatusRequest)(nil),  // 8: goclaw.v1.GetWorkflowStatusRequest
	(*TaskStatusDetail)(nil),          // 9: goclaw.v1.TaskStatusDetail
	(*GetWorkflowStatusResponse)(nil), // 10: goclaw.v1.GetWorkflowStatusResponse
	(*CancelWorkflowRequest)(nil),     // 11: goclaw.v1.CancelWorkflowRequest
	(*CancelWorkflowResponse)(nil),    // 12: goclaw.v1.CancelWorkflowResponse
	(*GetTaskResultRequest)(nil),      // 13: goclaw.v1.GetTaskResultRequest
	(*GetTaskResultResponse)(nil),     // 14: goclaw.v1.GetTaskResultResponse
	nil,                               // 15: goclaw.v1.TaskDefinition.MetadataEntry
	nil,                               // 16: goclaw.v1.SubmitWorkflowRequest.MetadataEntry
	(*Error)(nil),                     // 17: goclaw.v1.Error
	(*PaginationRequest)(nil),         // 18: goclaw.v1.PaginationRequest
	(*timestamppb.Timestamp)(nil),     // 19: google.protobuf.Timestamp
	(*PaginationResponse)(nil),        // 20: goclaw.v1.PaginationResponse
}
var file_goclaw_v1_workflow_proto_depIdxs = []int32{
	15, // 0: goclaw.v1.TaskDefinition.metadata:type_name -> goclaw.v1.TaskDefinition.MetadataEntry
	2,  // 1: goclaw.v1.SubmitWorkflowRequest.tasks:type_name -> goclaw.v1.TaskDefinition
	16, // 2: goclaw.v1.SubmitWorkflowRequest.metadata:type_name -> goclaw.v1.SubmitWorkflowRequest.MetadataEntry
	17, // 3: goclaw.v1.SubmitWorkflowResponse.error:type_name -> goclaw.v1.Error
	18, // 4: goclaw.v1.ListWorkflowsRequest.pagination:type_name -> goclaw.v1.PaginationRequest
	0,  // 5: goclaw.v1.ListWorkflowsRequest.status_filter:type_name -> goclaw.v1.WorkflowStatus
	0,  // 6: goclaw.v1.WorkflowSummary.status:type_name -> goclaw.v1.WorkflowStatus
	19, // 7: goclaw.v1.WorkflowSummary.created_at:type_name -> google.protobuf.Timestamp
	19, // 8: goclaw.v1.WorkflowSummary.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 9: goclaw.v1.ListWorkflowsResponse.workflows:type_name -> goclaw.v1.WorkflowSummary
	20, // 10: goclaw.v1.ListWorkflowsResponse.pagination:type_name -> goclaw.v1.PaginationResponse
	17, // 11: goclaw.v1.ListWorkflowsResponse.error:type_name -> goclaw.v1.Error
	1,  // 12: goclaw.v1.TaskStatusDetail.status:type_name -> goclaw.v1.TaskStatus
	19, // 13: goclaw.v1.TaskStatusDetail.started_at:type_name -> google.protobuf.Timestamp
	19, // 14: goclaw.v1.TaskStatusDetail.completed_at:type_name -> google.protobuf.Timestamp
	0,  // 15: goclaw.v1.GetWorkflowStatusResponse.status:type_name -> goclaw.v1.WorkflowStatus
	9,  // 16: goclaw.v1.GetWorkflowStatusResponse.tasks:type_name -> goclaw.v1.TaskStatusDetail
	19, // 17: goclaw.v1.GetWorkflowStatusResponse.created_at:type_name -> google.protobuf.Timestamp
	19, // 18: goclaw.v1.GetWorkflowStatusResponse.updated_at:type_name -> google.protobuf.Timestamp
	17, // 19: goclaw.v1.GetWorkflowStatusResponse.error:type_name -> goclaw.v1.Error
	17, // 20: goclaw.v1.CancelWorkflowResponse.error:type_name -> goclaw.v1.Error
	1,  // 21: goclaw.v1.GetTaskResultResponse.status:type_name -> goclaw.v1.TaskStatus
	17, // 22: goclaw.v1.GetTaskResultResponse.error:type_name -> goclaw.v1.Error
	3,  // 23: goclaw.v1.WorkflowService.SubmitWorkflow:input_type -> goclaw.v1.SubmitWorkflowRequest
	5,  // 24: goclaw.v1.WorkflowService.ListWorkflows:input_type -> goclaw.v1.ListWorkflowsRequest
	8,  // 25: goclaw.v1.WorkflowService.GetWorkflowStatus:input_type -> goclaw.v1.GetWorkflowStatusRequest
	11, // 26: goclaw.v1.WorkflowService.CancelWorkflow:input_type -> goclaw.v1.CancelWorkflowRequest
	13, // 27: goclaw.v1.WorkflowService.GetTaskResult:input_type -> goclaw.v1.GetTaskResultRequest
	4,  // 28: goclaw.v1.WorkflowService.SubmitWorkflow:output_type -> goclaw.v1.SubmitWorkflowResponse
	7,  // 29: goclaw.v1.WorkflowService.ListWorkflows:output_type -> goclaw.v1.ListWorkflowsResponse
	10, // 30: goclaw.v1.WorkflowService.GetWorkflowStatus:output_type -> goclaw.v1.GetWorkflowStatusResponse
	12, // 31: goclaw.v1.WorkflowService.CancelWorkflow:output_type -> goclaw.v1.CancelWorkflowResponse
	14, // 32: goclaw.v1.WorkflowService.GetTaskResult:output_type -> goclaw.v1.GetTaskResultResponse
	28, // [28:33] is the sub-list for method output_type
	23, // [23:28] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_goclaw_v1_workflow_proto_init() }
func file_goclaw_v1_workflow_proto_init() {
	if File_goclaw_v1_workflow_proto != nil {
		return
	}
	file_goclaw_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goclaw_v1_workflow_proto_rawDesc), len(file_goclaw_v1_workflow_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goclaw_v1_workflow_proto_goTypes,
		DependencyIndexes: file_goclaw_v1_workflow_proto_depIdxs,
		EnumInfos:         file_goclaw_v1_workflow_proto_enumTypes,
		MessageInfos:      file_goclaw_v1_workflow_proto_msgTypes,
	}.Build()
	File_goclaw_v1_workflow_proto = out.File
	file_goclaw_v1_workflow_proto_goTypes = nil
	file_goclaw_v1_workflow_proto_depIdxs = nil
}
